// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: connectionless_netmessages.proto
// Protobuf C++ Version: 7.35.1

#ifndef connectionless_5fnetmessages_2eproto_2epb_2eh
#define connectionless_5fnetmessages_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7035001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "netmessages.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_connectionless_5fnetmessages_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_connectionless_5fnetmessages_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_connectionless_5fnetmessages_2eproto;
}  // extern "C"
class C2S_CONNECTION_Message;
struct C2S_CONNECTION_MessageGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern C2S_CONNECTION_MessageGlobalsTypeInternal C2S_CONNECTION_Message_globals_;
extern const ::google::protobuf::internal::ClassDataFull C2S_CONNECTION_Message_class_data_;
#else
extern const C2S_CONNECTION_MessageGlobalsTypeInternal C2S_CONNECTION_Message_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
class C2S_CONNECT_Message;
struct C2S_CONNECT_MessageGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern C2S_CONNECT_MessageGlobalsTypeInternal C2S_CONNECT_Message_globals_;
extern const ::google::protobuf::internal::ClassDataFull C2S_CONNECT_Message_class_data_;
#else
extern const C2S_CONNECT_MessageGlobalsTypeInternal C2S_CONNECT_Message_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
class C2S_CONNECT_SameProcessCheck;
struct C2S_CONNECT_SameProcessCheckGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern C2S_CONNECT_SameProcessCheckGlobalsTypeInternal C2S_CONNECT_SameProcessCheck_globals_;
extern const ::google::protobuf::internal::ClassDataFull C2S_CONNECT_SameProcessCheck_class_data_;
#else
extern const C2S_CONNECT_SameProcessCheckGlobalsTypeInternal C2S_CONNECT_SameProcessCheck_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED C2S_CONNECT_SameProcessCheck final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:C2S_CONNECT_SameProcessCheck) */ {
 public:
  inline C2S_CONNECT_SameProcessCheck() : C2S_CONNECT_SameProcessCheck(nullptr) {}
  ~C2S_CONNECT_SameProcessCheck() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(C2S_CONNECT_SameProcessCheck* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(C2S_CONNECT_SameProcessCheck));
  }
#endif

  template <typename = void>
  explicit constexpr C2S_CONNECT_SameProcessCheck(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline C2S_CONNECT_SameProcessCheck(const C2S_CONNECT_SameProcessCheck& from) : C2S_CONNECT_SameProcessCheck(nullptr, from) {}
  inline C2S_CONNECT_SameProcessCheck(C2S_CONNECT_SameProcessCheck&& from) noexcept : C2S_CONNECT_SameProcessCheck(nullptr, ::std::move(from)) {}
  inline C2S_CONNECT_SameProcessCheck& operator=(const C2S_CONNECT_SameProcessCheck& from) {
    CopyFrom(from);
    return *this;
  }
  inline C2S_CONNECT_SameProcessCheck& operator=(C2S_CONNECT_SameProcessCheck&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const C2S_CONNECT_SameProcessCheck& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<C2S_CONNECT_SameProcessCheck>(&C2S_CONNECT_SameProcessCheck_globals_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(C2S_CONNECT_SameProcessCheck& a, C2S_CONNECT_SameProcessCheck& b) { a.Swap(&b); }
  inline void Swap(C2S_CONNECT_SameProcessCheck* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C2S_CONNECT_SameProcessCheck* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] C2S_CONNECT_SameProcessCheck* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<C2S_CONNECT_SameProcessCheck>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const C2S_CONNECT_SameProcessCheck& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const C2S_CONNECT_SameProcessCheck& from) { C2S_CONNECT_SameProcessCheck::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(C2S_CONNECT_SameProcessCheck* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "C2S_CONNECT_SameProcessCheck"; }

  explicit C2S_CONNECT_SameProcessCheck(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  C2S_CONNECT_SameProcessCheck(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const C2S_CONNECT_SameProcessCheck& from);
  C2S_CONNECT_SameProcessCheck(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, C2S_CONNECT_SameProcessCheck&& from) noexcept
      : C2S_CONNECT_SameProcessCheck(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kLocalhostProcessIdFieldNumber = 1,
    kKeyFieldNumber = 2,
  };
  // optional uint64 localhost_process_id = 1;
  [[nodiscard]] bool has_localhost_process_id()
      const;
  void clear_localhost_process_id() ;
  [[nodiscard]] ::uint64_t localhost_process_id() const;
  void set_localhost_process_id(::uint64_t value);

  private:
  ::uint64_t _internal_localhost_process_id() const;
  void _internal_set_localhost_process_id(::uint64_t value);

  public:
  // optional uint64 key = 2;
  [[nodiscard]] bool has_key()
      const;
  void clear_key() ;
  [[nodiscard]] ::uint64_t key() const;
  void set_key(::uint64_t value);

  private:
  ::uint64_t _internal_key() const;
  void _internal_set_key(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:C2S_CONNECT_SameProcessCheck)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<1, 2,
                          0, 0,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const C2S_CONNECT_SameProcessCheck& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint64_t localhost_process_id_;
    ::uint64_t key_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_connectionless_5fnetmessages_2eproto;
};
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED C2S_CONNECT_Message final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:C2S_CONNECT_Message) */ {
 public:
  inline C2S_CONNECT_Message() : C2S_CONNECT_Message(nullptr) {}
  ~C2S_CONNECT_Message() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(C2S_CONNECT_Message* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(C2S_CONNECT_Message));
  }
#endif

  template <typename = void>
  explicit constexpr C2S_CONNECT_Message(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline C2S_CONNECT_Message(const C2S_CONNECT_Message& from) : C2S_CONNECT_Message(nullptr, from) {}
  inline C2S_CONNECT_Message(C2S_CONNECT_Message&& from) noexcept : C2S_CONNECT_Message(nullptr, ::std::move(from)) {}
  inline C2S_CONNECT_Message& operator=(const C2S_CONNECT_Message& from) {
    CopyFrom(from);
    return *this;
  }
  inline C2S_CONNECT_Message& operator=(C2S_CONNECT_Message&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const C2S_CONNECT_Message& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<C2S_CONNECT_Message>(&C2S_CONNECT_Message_globals_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(C2S_CONNECT_Message& a, C2S_CONNECT_Message& b) { a.Swap(&b); }
  inline void Swap(C2S_CONNECT_Message* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C2S_CONNECT_Message* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] C2S_CONNECT_Message* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<C2S_CONNECT_Message>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const C2S_CONNECT_Message& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const C2S_CONNECT_Message& from) { C2S_CONNECT_Message::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(C2S_CONNECT_Message* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "C2S_CONNECT_Message"; }

  explicit C2S_CONNECT_Message(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  C2S_CONNECT_Message(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const C2S_CONNECT_Message& from);
  C2S_CONNECT_Message(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, C2S_CONNECT_Message&& from) noexcept
      : C2S_CONNECT_Message(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSplitplayersFieldNumber = 7,
    kEncryptedPasswordFieldNumber = 6,
    kAuthSteamFieldNumber = 8,
    kChallengeContextFieldNumber = 9,
    kLocalhostSameProcessCheckFieldNumber = 10,
    kHostVersionFieldNumber = 1,
    kAuthProtocolFieldNumber = 2,
    kReservationCookieFieldNumber = 4,
    kChallengeNumberFieldNumber = 3,
    kLowViolenceFieldNumber = 5,
  };
  // repeated .CCLCMsg_SplitPlayerConnect splitplayers = 7;
  [[nodiscard]] int splitplayers_size()
      const;
  private:
  int _internal_splitplayers_size() const;

  public:
  void clear_splitplayers() ;
  [[nodiscard]] const ::CCLCMsg_SplitPlayerConnect& splitplayers(int index) const;
  [[nodiscard]] ::CCLCMsg_SplitPlayerConnect* PROTOBUF_NONNULL mutable_splitplayers(int index);
  ::CCLCMsg_SplitPlayerConnect* PROTOBUF_NONNULL add_splitplayers();
  [[nodiscard]] const ::google::protobuf::RepeatedPtrField<::CCLCMsg_SplitPlayerConnect>&
  splitplayers() const;
  [[nodiscard]] ::google::protobuf::RepeatedPtrField<::CCLCMsg_SplitPlayerConnect>* PROTOBUF_NONNULL
  mutable_splitplayers();

  private:
  const ::google::protobuf::RepeatedPtrField<::CCLCMsg_SplitPlayerConnect>& _internal_splitplayers() const;
  ::google::protobuf::RepeatedPtrField<::CCLCMsg_SplitPlayerConnect>* PROTOBUF_NONNULL _internal_mutable_splitplayers();

  public:
  // optional bytes encrypted_password = 6;
  [[nodiscard]] bool has_encrypted_password()
      const;
  void clear_encrypted_password() ;
  [[nodiscard]] const ::std::string& encrypted_password() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_encrypted_password(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_encrypted_password();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_encrypted_password();
  void set_allocated_encrypted_password(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_encrypted_password() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_encrypted_password(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_encrypted_password();

  public:
  // optional bytes auth_steam = 8;
  [[nodiscard]] bool has_auth_steam()
      const;
  void clear_auth_steam() ;
  [[nodiscard]] const ::std::string& auth_steam() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_auth_steam(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_auth_steam();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_auth_steam();
  void set_allocated_auth_steam(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_auth_steam() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_auth_steam(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_auth_steam();

  public:
  // optional string challenge_context = 9;
  [[nodiscard]] bool has_challenge_context()
      const;
  void clear_challenge_context() ;
  [[nodiscard]] const ::std::string& challenge_context() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_challenge_context(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_challenge_context();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_challenge_context();
  void set_allocated_challenge_context(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_challenge_context() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_challenge_context(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_challenge_context();

  public:
  // optional .C2S_CONNECT_SameProcessCheck localhost_same_process_check = 10;
  [[nodiscard]] bool has_localhost_same_process_check()
      const;
  void clear_localhost_same_process_check() ;
  [[nodiscard]] const ::C2S_CONNECT_SameProcessCheck& localhost_same_process_check() const;
  [[nodiscard]] ::C2S_CONNECT_SameProcessCheck* PROTOBUF_NULLABLE release_localhost_same_process_check();
  ::C2S_CONNECT_SameProcessCheck* PROTOBUF_NONNULL mutable_localhost_same_process_check();
  void set_allocated_localhost_same_process_check(::C2S_CONNECT_SameProcessCheck* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_localhost_same_process_check(::C2S_CONNECT_SameProcessCheck* PROTOBUF_NULLABLE value);
  ::C2S_CONNECT_SameProcessCheck* PROTOBUF_NULLABLE unsafe_arena_release_localhost_same_process_check();

  private:
  const ::C2S_CONNECT_SameProcessCheck& _internal_localhost_same_process_check() const;
  ::C2S_CONNECT_SameProcessCheck* PROTOBUF_NONNULL _internal_mutable_localhost_same_process_check();

  public:
  // optional uint32 host_version = 1;
  [[nodiscard]] bool has_host_version()
      const;
  void clear_host_version() ;
  [[nodiscard]] ::uint32_t host_version() const;
  void set_host_version(::uint32_t value);

  private:
  ::uint32_t _internal_host_version() const;
  void _internal_set_host_version(::uint32_t value);

  public:
  // optional uint32 auth_protocol = 2;
  [[nodiscard]] bool has_auth_protocol()
      const;
  void clear_auth_protocol() ;
  [[nodiscard]] ::uint32_t auth_protocol() const;
  void set_auth_protocol(::uint32_t value);

  private:
  ::uint32_t _internal_auth_protocol() const;
  void _internal_set_auth_protocol(::uint32_t value);

  public:
  // optional fixed64 reservation_cookie = 4;
  [[nodiscard]] bool has_reservation_cookie()
      const;
  void clear_reservation_cookie() ;
  [[nodiscard]] ::uint64_t reservation_cookie() const;
  void set_reservation_cookie(::uint64_t value);

  private:
  ::uint64_t _internal_reservation_cookie() const;
  void _internal_set_reservation_cookie(::uint64_t value);

  public:
  // optional uint32 challenge_number = 3;
  [[nodiscard]] bool has_challenge_number()
      const;
  void clear_challenge_number() ;
  [[nodiscard]] ::uint32_t challenge_number() const;
  void set_challenge_number(::uint32_t value);

  private:
  ::uint32_t _internal_challenge_number() const;
  void _internal_set_challenge_number(::uint32_t value);

  public:
  // optional bool low_violence = 5;
  [[nodiscard]] bool has_low_violence()
      const;
  void clear_low_violence() ;
  [[nodiscard]] bool low_violence() const;
  void set_low_violence(bool value);

  private:
  bool _internal_low_violence() const;
  void _internal_set_low_violence(bool value);

  public:
  // @@protoc_insertion_point(class_scope:C2S_CONNECT_Message)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<4, 10,
                          2, 0,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const C2S_CONNECT_Message& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::CCLCMsg_SplitPlayerConnect > splitplayers_;
    ::google::protobuf::internal::ArenaStringPtr encrypted_password_;
    ::google::protobuf::internal::ArenaStringPtr auth_steam_;
    ::google::protobuf::internal::ArenaStringPtr challenge_context_;
    ::C2S_CONNECT_SameProcessCheck* PROTOBUF_NULLABLE localhost_same_process_check_;
    ::uint32_t host_version_;
    ::uint32_t auth_protocol_;
    ::uint64_t reservation_cookie_;
    ::uint32_t challenge_number_;
    bool low_violence_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_connectionless_5fnetmessages_2eproto;
};
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED C2S_CONNECTION_Message final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:C2S_CONNECTION_Message) */ {
 public:
  inline C2S_CONNECTION_Message() : C2S_CONNECTION_Message(nullptr) {}
  ~C2S_CONNECTION_Message() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(C2S_CONNECTION_Message* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(C2S_CONNECTION_Message));
  }
#endif

  template <typename = void>
  explicit constexpr C2S_CONNECTION_Message(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline C2S_CONNECTION_Message(const C2S_CONNECTION_Message& from) : C2S_CONNECTION_Message(nullptr, from) {}
  inline C2S_CONNECTION_Message(C2S_CONNECTION_Message&& from) noexcept : C2S_CONNECTION_Message(nullptr, ::std::move(from)) {}
  inline C2S_CONNECTION_Message& operator=(const C2S_CONNECTION_Message& from) {
    CopyFrom(from);
    return *this;
  }
  inline C2S_CONNECTION_Message& operator=(C2S_CONNECTION_Message&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const C2S_CONNECTION_Message& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<C2S_CONNECTION_Message>(&C2S_CONNECTION_Message_globals_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(C2S_CONNECTION_Message& a, C2S_CONNECTION_Message& b) { a.Swap(&b); }
  inline void Swap(C2S_CONNECTION_Message* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C2S_CONNECTION_Message* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] C2S_CONNECTION_Message* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<C2S_CONNECTION_Message>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const C2S_CONNECTION_Message& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const C2S_CONNECTION_Message& from) { C2S_CONNECTION_Message::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(C2S_CONNECTION_Message* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "C2S_CONNECTION_Message"; }

  explicit C2S_CONNECTION_Message(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  C2S_CONNECTION_Message(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const C2S_CONNECTION_Message& from);
  C2S_CONNECTION_Message(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, C2S_CONNECTION_Message&& from) noexcept
      : C2S_CONNECTION_Message(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kAddonNameFieldNumber = 1,
    kLocalhostSameProcessCheckFieldNumber = 2,
  };
  // optional string addon_name = 1;
  [[nodiscard]] bool has_addon_name()
      const;
  void clear_addon_name() ;
  [[nodiscard]] const ::std::string& addon_name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_addon_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_addon_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_addon_name();
  void set_allocated_addon_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_addon_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_addon_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_addon_name();

  public:
  // optional .C2S_CONNECT_SameProcessCheck localhost_same_process_check = 2;
  [[nodiscard]] bool has_localhost_same_process_check()
      const;
  void clear_localhost_same_process_check() ;
  [[nodiscard]] const ::C2S_CONNECT_SameProcessCheck& localhost_same_process_check() const;
  [[nodiscard]] ::C2S_CONNECT_SameProcessCheck* PROTOBUF_NULLABLE release_localhost_same_process_check();
  ::C2S_CONNECT_SameProcessCheck* PROTOBUF_NONNULL mutable_localhost_same_process_check();
  void set_allocated_localhost_same_process_check(::C2S_CONNECT_SameProcessCheck* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_localhost_same_process_check(::C2S_CONNECT_SameProcessCheck* PROTOBUF_NULLABLE value);
  ::C2S_CONNECT_SameProcessCheck* PROTOBUF_NULLABLE unsafe_arena_release_localhost_same_process_check();

  private:
  const ::C2S_CONNECT_SameProcessCheck& _internal_localhost_same_process_check() const;
  ::C2S_CONNECT_SameProcessCheck* PROTOBUF_NONNULL _internal_mutable_localhost_same_process_check();

  public:
  // @@protoc_insertion_point(class_scope:C2S_CONNECTION_Message)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<1, 2,
                          1, 0,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const C2S_CONNECTION_Message& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr addon_name_;
    ::C2S_CONNECT_SameProcessCheck* PROTOBUF_NULLABLE localhost_same_process_check_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_connectionless_5fnetmessages_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// C2S_CONNECT_SameProcessCheck

// optional uint64 localhost_process_id = 1;
inline bool C2S_CONNECT_SameProcessCheck::has_localhost_process_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void C2S_CONNECT_SameProcessCheck::clear_localhost_process_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.localhost_process_id_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline ::uint64_t C2S_CONNECT_SameProcessCheck::localhost_process_id() const {
  // @@protoc_insertion_point(field_get:C2S_CONNECT_SameProcessCheck.localhost_process_id)
  return _internal_localhost_process_id();
}
inline void C2S_CONNECT_SameProcessCheck::set_localhost_process_id(::uint64_t value) {
  _internal_set_localhost_process_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:C2S_CONNECT_SameProcessCheck.localhost_process_id)
}
inline ::uint64_t C2S_CONNECT_SameProcessCheck::_internal_localhost_process_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.localhost_process_id_;
}
inline void C2S_CONNECT_SameProcessCheck::_internal_set_localhost_process_id(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.localhost_process_id_ = value;
}

// optional uint64 key = 2;
inline bool C2S_CONNECT_SameProcessCheck::has_key() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void C2S_CONNECT_SameProcessCheck::clear_key() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.key_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline ::uint64_t C2S_CONNECT_SameProcessCheck::key() const {
  // @@protoc_insertion_point(field_get:C2S_CONNECT_SameProcessCheck.key)
  return _internal_key();
}
inline void C2S_CONNECT_SameProcessCheck::set_key(::uint64_t value) {
  _internal_set_key(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:C2S_CONNECT_SameProcessCheck.key)
}
inline ::uint64_t C2S_CONNECT_SameProcessCheck::_internal_key() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.key_;
}
inline void C2S_CONNECT_SameProcessCheck::_internal_set_key(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.key_ = value;
}

// -------------------------------------------------------------------

// C2S_CONNECT_Message

// optional uint32 host_version = 1;
inline bool C2S_CONNECT_Message::has_host_version() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000020U);
  return value;
}
inline void C2S_CONNECT_Message::clear_host_version() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.host_version_ = 0u;
  ClearHasBit(_impl_._has_bits_[0], 0x00000020U);
}
inline ::uint32_t C2S_CONNECT_Message::host_version() const {
  // @@protoc_insertion_point(field_get:C2S_CONNECT_Message.host_version)
  return _internal_host_version();
}
inline void C2S_CONNECT_Message::set_host_version(::uint32_t value) {
  _internal_set_host_version(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:C2S_CONNECT_Message.host_version)
}
inline ::uint32_t C2S_CONNECT_Message::_internal_host_version() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.host_version_;
}
inline void C2S_CONNECT_Message::_internal_set_host_version(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.host_version_ = value;
}

// optional uint32 auth_protocol = 2;
inline bool C2S_CONNECT_Message::has_auth_protocol() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000040U);
  return value;
}
inline void C2S_CONNECT_Message::clear_auth_protocol() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.auth_protocol_ = 0u;
  ClearHasBit(_impl_._has_bits_[0], 0x00000040U);
}
inline ::uint32_t C2S_CONNECT_Message::auth_protocol() const {
  // @@protoc_insertion_point(field_get:C2S_CONNECT_Message.auth_protocol)
  return _internal_auth_protocol();
}
inline void C2S_CONNECT_Message::set_auth_protocol(::uint32_t value) {
  _internal_set_auth_protocol(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:C2S_CONNECT_Message.auth_protocol)
}
inline ::uint32_t C2S_CONNECT_Message::_internal_auth_protocol() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.auth_protocol_;
}
inline void C2S_CONNECT_Message::_internal_set_auth_protocol(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.auth_protocol_ = value;
}

// optional uint32 challenge_number = 3;
inline bool C2S_CONNECT_Message::has_challenge_number() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000100U);
  return value;
}
inline void C2S_CONNECT_Message::clear_challenge_number() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.challenge_number_ = 0u;
  ClearHasBit(_impl_._has_bits_[0], 0x00000100U);
}
inline ::uint32_t C2S_CONNECT_Message::challenge_number() const {
  // @@protoc_insertion_point(field_get:C2S_CONNECT_Message.challenge_number)
  return _internal_challenge_number();
}
inline void C2S_CONNECT_Message::set_challenge_number(::uint32_t value) {
  _internal_set_challenge_number(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000100U);
  // @@protoc_insertion_point(field_set:C2S_CONNECT_Message.challenge_number)
}
inline ::uint32_t C2S_CONNECT_Message::_internal_challenge_number() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.challenge_number_;
}
inline void C2S_CONNECT_Message::_internal_set_challenge_number(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.challenge_number_ = value;
}

// optional fixed64 reservation_cookie = 4;
inline bool C2S_CONNECT_Message::has_reservation_cookie() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000080U);
  return value;
}
inline void C2S_CONNECT_Message::clear_reservation_cookie() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.reservation_cookie_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0], 0x00000080U);
}
inline ::uint64_t C2S_CONNECT_Message::reservation_cookie() const {
  // @@protoc_insertion_point(field_get:C2S_CONNECT_Message.reservation_cookie)
  return _internal_reservation_cookie();
}
inline void C2S_CONNECT_Message::set_reservation_cookie(::uint64_t value) {
  _internal_set_reservation_cookie(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_set:C2S_CONNECT_Message.reservation_cookie)
}
inline ::uint64_t C2S_CONNECT_Message::_internal_reservation_cookie() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.reservation_cookie_;
}
inline void C2S_CONNECT_Message::_internal_set_reservation_cookie(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.reservation_cookie_ = value;
}

// optional bool low_violence = 5;
inline bool C2S_CONNECT_Message::has_low_violence() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000200U);
  return value;
}
inline void C2S_CONNECT_Message::clear_low_violence() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.low_violence_ = false;
  ClearHasBit(_impl_._has_bits_[0], 0x00000200U);
}
inline bool C2S_CONNECT_Message::low_violence() const {
  // @@protoc_insertion_point(field_get:C2S_CONNECT_Message.low_violence)
  return _internal_low_violence();
}
inline void C2S_CONNECT_Message::set_low_violence(bool value) {
  _internal_set_low_violence(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000200U);
  // @@protoc_insertion_point(field_set:C2S_CONNECT_Message.low_violence)
}
inline bool C2S_CONNECT_Message::_internal_low_violence() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.low_violence_;
}
inline void C2S_CONNECT_Message::_internal_set_low_violence(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.low_violence_ = value;
}

// optional bytes encrypted_password = 6;
inline bool C2S_CONNECT_Message::has_encrypted_password() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void C2S_CONNECT_Message::clear_encrypted_password() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.encrypted_password_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline const ::std::string& C2S_CONNECT_Message::encrypted_password() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:C2S_CONNECT_Message.encrypted_password)
  return _internal_encrypted_password();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void C2S_CONNECT_Message::set_encrypted_password(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.encrypted_password_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:C2S_CONNECT_Message.encrypted_password)
}
inline ::std::string* PROTOBUF_NONNULL C2S_CONNECT_Message::mutable_encrypted_password()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_encrypted_password();
  // @@protoc_insertion_point(field_mutable:C2S_CONNECT_Message.encrypted_password)
  return _s;
}
inline const ::std::string& C2S_CONNECT_Message::_internal_encrypted_password() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.encrypted_password_.Get();
}
inline void C2S_CONNECT_Message::_internal_set_encrypted_password(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.encrypted_password_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL C2S_CONNECT_Message::_internal_mutable_encrypted_password() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.encrypted_password_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE C2S_CONNECT_Message::release_encrypted_password() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:C2S_CONNECT_Message.encrypted_password)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.encrypted_password_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.encrypted_password_.Set("", GetArena());
  }
  return released;
}
inline void C2S_CONNECT_Message::set_allocated_encrypted_password(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.encrypted_password_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.encrypted_password_.IsDefault()) {
    _impl_.encrypted_password_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:C2S_CONNECT_Message.encrypted_password)
}

// repeated .CCLCMsg_SplitPlayerConnect splitplayers = 7;
inline int C2S_CONNECT_Message::_internal_splitplayers_size() const {
  return _internal_splitplayers().size();
}
inline int C2S_CONNECT_Message::splitplayers_size() const {
  return _internal_splitplayers_size();
}
inline const ::CCLCMsg_SplitPlayerConnect& C2S_CONNECT_Message::splitplayers(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:C2S_CONNECT_Message.splitplayers)
  return _internal_splitplayers().Get(index);
}
inline ::CCLCMsg_SplitPlayerConnect* PROTOBUF_NONNULL C2S_CONNECT_Message::mutable_splitplayers(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:C2S_CONNECT_Message.splitplayers)
  return _internal_mutable_splitplayers()->Mutable(index);
}
inline ::CCLCMsg_SplitPlayerConnect* PROTOBUF_NONNULL C2S_CONNECT_Message::add_splitplayers()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::CCLCMsg_SplitPlayerConnect* _add =
      _internal_mutable_splitplayers()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:C2S_CONNECT_Message.splitplayers)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::CCLCMsg_SplitPlayerConnect>& C2S_CONNECT_Message::splitplayers() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:C2S_CONNECT_Message.splitplayers)
  return _internal_splitplayers();
}
inline ::google::protobuf::RepeatedPtrField<::CCLCMsg_SplitPlayerConnect>* PROTOBUF_NONNULL
C2S_CONNECT_Message::mutable_splitplayers() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:C2S_CONNECT_Message.splitplayers)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_splitplayers();
}
inline const ::google::protobuf::RepeatedPtrField<::CCLCMsg_SplitPlayerConnect>&
C2S_CONNECT_Message::_internal_splitplayers() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.splitplayers_;
}
inline ::google::protobuf::RepeatedPtrField<::CCLCMsg_SplitPlayerConnect>* PROTOBUF_NONNULL
C2S_CONNECT_Message::_internal_mutable_splitplayers() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.splitplayers_;
}

// optional bytes auth_steam = 8;
inline bool C2S_CONNECT_Message::has_auth_steam() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void C2S_CONNECT_Message::clear_auth_steam() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.auth_steam_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
}
inline const ::std::string& C2S_CONNECT_Message::auth_steam() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:C2S_CONNECT_Message.auth_steam)
  return _internal_auth_steam();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void C2S_CONNECT_Message::set_auth_steam(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.auth_steam_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:C2S_CONNECT_Message.auth_steam)
}
inline ::std::string* PROTOBUF_NONNULL C2S_CONNECT_Message::mutable_auth_steam()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_auth_steam();
  // @@protoc_insertion_point(field_mutable:C2S_CONNECT_Message.auth_steam)
  return _s;
}
inline const ::std::string& C2S_CONNECT_Message::_internal_auth_steam() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.auth_steam_.Get();
}
inline void C2S_CONNECT_Message::_internal_set_auth_steam(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.auth_steam_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL C2S_CONNECT_Message::_internal_mutable_auth_steam() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.auth_steam_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE C2S_CONNECT_Message::release_auth_steam() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:C2S_CONNECT_Message.auth_steam)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.auth_steam_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.auth_steam_.Set("", GetArena());
  }
  return released;
}
inline void C2S_CONNECT_Message::set_allocated_auth_steam(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.auth_steam_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.auth_steam_.IsDefault()) {
    _impl_.auth_steam_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:C2S_CONNECT_Message.auth_steam)
}

// optional string challenge_context = 9;
inline bool C2S_CONNECT_Message::has_challenge_context() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  return value;
}
inline void C2S_CONNECT_Message::clear_challenge_context() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.challenge_context_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
}
inline const ::std::string& C2S_CONNECT_Message::challenge_context() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:C2S_CONNECT_Message.challenge_context)
  return _internal_challenge_context();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void C2S_CONNECT_Message::set_challenge_context(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  _impl_.challenge_context_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:C2S_CONNECT_Message.challenge_context)
}
inline ::std::string* PROTOBUF_NONNULL C2S_CONNECT_Message::mutable_challenge_context()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::std::string* _s = _internal_mutable_challenge_context();
  // @@protoc_insertion_point(field_mutable:C2S_CONNECT_Message.challenge_context)
  return _s;
}
inline const ::std::string& C2S_CONNECT_Message::_internal_challenge_context() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.challenge_context_.Get();
}
inline void C2S_CONNECT_Message::_internal_set_challenge_context(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.challenge_context_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL C2S_CONNECT_Message::_internal_mutable_challenge_context() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.challenge_context_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE C2S_CONNECT_Message::release_challenge_context() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:C2S_CONNECT_Message.challenge_context)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000008U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  auto* released = _impl_.challenge_context_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.challenge_context_.Set("", GetArena());
  }
  return released;
}
inline void C2S_CONNECT_Message::set_allocated_challenge_context(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  _impl_.challenge_context_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.challenge_context_.IsDefault()) {
    _impl_.challenge_context_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:C2S_CONNECT_Message.challenge_context)
}

// optional .C2S_CONNECT_SameProcessCheck localhost_same_process_check = 10;
inline bool C2S_CONNECT_Message::has_localhost_same_process_check() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000010U);
  PROTOBUF_ASSUME(!value || _impl_.localhost_same_process_check_ != nullptr);
  return value;
}
inline void C2S_CONNECT_Message::clear_localhost_same_process_check() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.localhost_same_process_check_ != nullptr) _impl_.localhost_same_process_check_->Clear();
  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
}
inline const ::C2S_CONNECT_SameProcessCheck& C2S_CONNECT_Message::_internal_localhost_same_process_check() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::C2S_CONNECT_SameProcessCheck* p = _impl_.localhost_same_process_check_;
  return p != nullptr ? *p : *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<::C2S_CONNECT_SameProcessCheck>(&::C2S_CONNECT_SameProcessCheck_globals_);
}
inline const ::C2S_CONNECT_SameProcessCheck& C2S_CONNECT_Message::localhost_same_process_check() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:C2S_CONNECT_Message.localhost_same_process_check)
  return _internal_localhost_same_process_check();
}
inline void C2S_CONNECT_Message::unsafe_arena_set_allocated_localhost_same_process_check(
    ::C2S_CONNECT_SameProcessCheck* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.localhost_same_process_check_);
  }
  _impl_.localhost_same_process_check_ = reinterpret_cast<::C2S_CONNECT_SameProcessCheck*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:C2S_CONNECT_Message.localhost_same_process_check)
}
inline ::C2S_CONNECT_SameProcessCheck* PROTOBUF_NULLABLE C2S_CONNECT_Message::release_localhost_same_process_check() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  ::C2S_CONNECT_SameProcessCheck* released = _impl_.localhost_same_process_check_;
  _impl_.localhost_same_process_check_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::C2S_CONNECT_SameProcessCheck* PROTOBUF_NULLABLE C2S_CONNECT_Message::unsafe_arena_release_localhost_same_process_check() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:C2S_CONNECT_Message.localhost_same_process_check)

  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  ::C2S_CONNECT_SameProcessCheck* temp = _impl_.localhost_same_process_check_;
  _impl_.localhost_same_process_check_ = nullptr;
  return temp;
}
inline ::C2S_CONNECT_SameProcessCheck* PROTOBUF_NONNULL C2S_CONNECT_Message::_internal_mutable_localhost_same_process_check() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.localhost_same_process_check_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::C2S_CONNECT_SameProcessCheck>(GetArena());
    _impl_.localhost_same_process_check_ = reinterpret_cast<::C2S_CONNECT_SameProcessCheck*>(p);
  }
  return _impl_.localhost_same_process_check_;
}
inline ::C2S_CONNECT_SameProcessCheck* PROTOBUF_NONNULL C2S_CONNECT_Message::mutable_localhost_same_process_check()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  ::C2S_CONNECT_SameProcessCheck* _msg = _internal_mutable_localhost_same_process_check();
  // @@protoc_insertion_point(field_mutable:C2S_CONNECT_Message.localhost_same_process_check)
  return _msg;
}
inline void C2S_CONNECT_Message::set_allocated_localhost_same_process_check(::C2S_CONNECT_SameProcessCheck* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.localhost_same_process_check_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  }

  _impl_.localhost_same_process_check_ = reinterpret_cast<::C2S_CONNECT_SameProcessCheck*>(value);
  // @@protoc_insertion_point(field_set_allocated:C2S_CONNECT_Message.localhost_same_process_check)
}

// -------------------------------------------------------------------

// C2S_CONNECTION_Message

// optional string addon_name = 1;
inline bool C2S_CONNECTION_Message::has_addon_name() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void C2S_CONNECTION_Message::clear_addon_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.addon_name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline const ::std::string& C2S_CONNECTION_Message::addon_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:C2S_CONNECTION_Message.addon_name)
  return _internal_addon_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void C2S_CONNECTION_Message::set_addon_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.addon_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:C2S_CONNECTION_Message.addon_name)
}
inline ::std::string* PROTOBUF_NONNULL C2S_CONNECTION_Message::mutable_addon_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_addon_name();
  // @@protoc_insertion_point(field_mutable:C2S_CONNECTION_Message.addon_name)
  return _s;
}
inline const ::std::string& C2S_CONNECTION_Message::_internal_addon_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.addon_name_.Get();
}
inline void C2S_CONNECTION_Message::_internal_set_addon_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.addon_name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL C2S_CONNECTION_Message::_internal_mutable_addon_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.addon_name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE C2S_CONNECTION_Message::release_addon_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:C2S_CONNECTION_Message.addon_name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.addon_name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.addon_name_.Set("", GetArena());
  }
  return released;
}
inline void C2S_CONNECTION_Message::set_allocated_addon_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.addon_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.addon_name_.IsDefault()) {
    _impl_.addon_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:C2S_CONNECTION_Message.addon_name)
}

// optional .C2S_CONNECT_SameProcessCheck localhost_same_process_check = 2;
inline bool C2S_CONNECTION_Message::has_localhost_same_process_check() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  PROTOBUF_ASSUME(!value || _impl_.localhost_same_process_check_ != nullptr);
  return value;
}
inline void C2S_CONNECTION_Message::clear_localhost_same_process_check() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.localhost_same_process_check_ != nullptr) _impl_.localhost_same_process_check_->Clear();
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline const ::C2S_CONNECT_SameProcessCheck& C2S_CONNECTION_Message::_internal_localhost_same_process_check() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::C2S_CONNECT_SameProcessCheck* p = _impl_.localhost_same_process_check_;
  return p != nullptr ? *p : *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<::C2S_CONNECT_SameProcessCheck>(&::C2S_CONNECT_SameProcessCheck_globals_);
}
inline const ::C2S_CONNECT_SameProcessCheck& C2S_CONNECTION_Message::localhost_same_process_check() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:C2S_CONNECTION_Message.localhost_same_process_check)
  return _internal_localhost_same_process_check();
}
inline void C2S_CONNECTION_Message::unsafe_arena_set_allocated_localhost_same_process_check(
    ::C2S_CONNECT_SameProcessCheck* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.localhost_same_process_check_);
  }
  _impl_.localhost_same_process_check_ = reinterpret_cast<::C2S_CONNECT_SameProcessCheck*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:C2S_CONNECTION_Message.localhost_same_process_check)
}
inline ::C2S_CONNECT_SameProcessCheck* PROTOBUF_NULLABLE C2S_CONNECTION_Message::release_localhost_same_process_check() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::C2S_CONNECT_SameProcessCheck* released = _impl_.localhost_same_process_check_;
  _impl_.localhost_same_process_check_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::C2S_CONNECT_SameProcessCheck* PROTOBUF_NULLABLE C2S_CONNECTION_Message::unsafe_arena_release_localhost_same_process_check() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:C2S_CONNECTION_Message.localhost_same_process_check)

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::C2S_CONNECT_SameProcessCheck* temp = _impl_.localhost_same_process_check_;
  _impl_.localhost_same_process_check_ = nullptr;
  return temp;
}
inline ::C2S_CONNECT_SameProcessCheck* PROTOBUF_NONNULL C2S_CONNECTION_Message::_internal_mutable_localhost_same_process_check() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.localhost_same_process_check_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::C2S_CONNECT_SameProcessCheck>(GetArena());
    _impl_.localhost_same_process_check_ = reinterpret_cast<::C2S_CONNECT_SameProcessCheck*>(p);
  }
  return _impl_.localhost_same_process_check_;
}
inline ::C2S_CONNECT_SameProcessCheck* PROTOBUF_NONNULL C2S_CONNECTION_Message::mutable_localhost_same_process_check()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::C2S_CONNECT_SameProcessCheck* _msg = _internal_mutable_localhost_same_process_check();
  // @@protoc_insertion_point(field_mutable:C2S_CONNECTION_Message.localhost_same_process_check)
  return _msg;
}
inline void C2S_CONNECTION_Message::set_allocated_localhost_same_process_check(::C2S_CONNECT_SameProcessCheck* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.localhost_same_process_check_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }

  _impl_.localhost_same_process_check_ = reinterpret_cast<::C2S_CONNECT_SameProcessCheck*>(value);
  // @@protoc_insertion_point(field_set_allocated:C2S_CONNECTION_Message.localhost_same_process_check)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // connectionless_5fnetmessages_2eproto_2epb_2eh
