// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: engine_gcmessages.proto
// Protobuf C++ Version: 7.35.1

#include "engine_gcmessages.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
#ifdef PROTOBUF_MESSAGE_GLOBALS
namespace {
PROTOBUF_CONSTINIT ::google::protobuf::internal::ReflectionData
    file_reflection_data[] = {
        // ::CEngineGotvSyncPacket
        {&::_pbi::kDescriptorMethods, &::descriptor_table_engine_5fgcmessages_2eproto, /* tracker*/ nullptr,},
};
}  // namespace
#endif
class CEngineGotvSyncPacket::_Internal {
 public:
  using HasBits = decltype(::std::declval<CEngineGotvSyncPacket>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_._has_bits_);
};

constexpr CEngineGotvSyncPacket::ParseTableT_ CEngineGotvSyncPacket::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_._has_bits_),
      0, // no _extensions_
      11, 120,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294965312,  // skipmap
      offsetof(ParseTableT_, field_entries),
      10,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::CEngineGotvSyncPacket>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      {::_pbi::TcParser::MiniParse, {}},
      // optional uint64 match_id = 1;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CEngineGotvSyncPacket, _impl_.match_id_), 0>(),
       {8, 0, 0,
        PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_.match_id_)}},
      // optional uint32 instance_id = 2;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CEngineGotvSyncPacket, _impl_.instance_id_), 1>(),
       {16, 1, 0,
        PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_.instance_id_)}},
      // optional uint32 signupfragment = 3;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CEngineGotvSyncPacket, _impl_.signupfragment_), 2>(),
       {24, 2, 0,
        PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_.signupfragment_)}},
      // optional uint32 currentfragment = 4;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CEngineGotvSyncPacket, _impl_.currentfragment_), 3>(),
       {32, 3, 0,
        PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_.currentfragment_)}},
      // optional float tickrate = 5;
      {::_pbi::TcParser::FastF32S1,
       {45, 4, 0,
        PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_.tickrate_)}},
      // optional uint32 tick = 6;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CEngineGotvSyncPacket, _impl_.tick_), 5>(),
       {48, 5, 0,
        PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_.tick_)}},
      {::_pbi::TcParser::MiniParse, {}},
      // optional float rtdelay = 8;
      {::_pbi::TcParser::FastF32S1,
       {69, 6, 0,
        PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_.rtdelay_)}},
      // optional float rcvage = 9;
      {::_pbi::TcParser::FastF32S1,
       {77, 7, 0,
        PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_.rcvage_)}},
      // optional float keyframe_interval = 10;
      {::_pbi::TcParser::FastF32S1,
       {85, 8, 0,
        PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_.keyframe_interval_)}},
      // optional uint32 cdndelay = 11;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CEngineGotvSyncPacket, _impl_.cdndelay_), 9>(),
       {88, 9, 0,
        PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_.cdndelay_)}},
      {::_pbi::TcParser::MiniParse, {}},
      {::_pbi::TcParser::MiniParse, {}},
      {::_pbi::TcParser::MiniParse, {}},
      {::_pbi::TcParser::MiniParse, {}},
    }}, {{
      65535, 65535
    }}, {{
      // optional uint64 match_id = 1;
      {PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_.match_id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
      // optional uint32 instance_id = 2;
      {PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_.instance_id_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
      // optional uint32 signupfragment = 3;
      {PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_.signupfragment_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
      // optional uint32 currentfragment = 4;
      {PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_.currentfragment_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
      // optional float tickrate = 5;
      {PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_.tickrate_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
      // optional uint32 tick = 6;
      {PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_.tick_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
      // optional float rtdelay = 8;
      {PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_.rtdelay_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
      // optional float rcvage = 9;
      {PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_.rcvage_), _Internal::kHasBitsOffset + 7, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
      // optional float keyframe_interval = 10;
      {PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_.keyframe_interval_), _Internal::kHasBitsOffset + 8, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
      // optional uint32 cdndelay = 11;
      {PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_.cdndelay_), _Internal::kHasBitsOffset + 9, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    }},
    // no aux_entries
    {{
    }},
  };
}


inline constexpr CEngineGotvSyncPacket::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        match_id_{::uint64_t{0u}},
        instance_id_{0u},
        signupfragment_{0u},
        currentfragment_{0u},
        tickrate_{0},
        tick_{0u},
        rtdelay_{0},
        rcvage_{0},
        keyframe_interval_{0},
        cdndelay_{0u} {}

template <typename>
constexpr CEngineGotvSyncPacket::CEngineGotvSyncPacket(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::Message(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL CEngineGotvSyncPacket::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CEngineGotvSyncPacket(arena);
}
constexpr auto CEngineGotvSyncPacket::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(CEngineGotvSyncPacket), alignof(CEngineGotvSyncPacket));
}
constexpr auto CEngineGotvSyncPacket::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &CEngineGotvSyncPacket::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CEngineGotvSyncPacket>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CEngineGotvSyncPacket::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CEngineGotvSyncPacket>(), &CEngineGotvSyncPacket::ByteSizeLong,
              &CEngineGotvSyncPacket::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[0],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_engine_5fgcmessages_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct CEngineGotvSyncPacketGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr CEngineGotvSyncPacketGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 CEngineGotvSyncPacket_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(CEngineGotvSyncPacket::InternalGenerateClassData_(
            _default, &CEngineGotvSyncPacket_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<CEngineGotvSyncPacket>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~CEngineGotvSyncPacketGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) CEngineGotvSyncPacket _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<CEngineGotvSyncPacket>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacketGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST CEngineGotvSyncPacketGlobalsTypeInternal CEngineGotvSyncPacket_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* CEngineGotvSyncPacket_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return CEngineGotvSyncPacket_globals_.GetClassData();
#else
  return CEngineGotvSyncPacket_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_engine_5fgcmessages_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_engine_5fgcmessages_2eproto = nullptr;
const ::uint32_t
    TableStruct_engine_5fgcmessages_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::CEngineGotvSyncPacket, _impl_._has_bits_),
        13, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::CEngineGotvSyncPacket, _impl_.match_id_),
        PROTOBUF_FIELD_OFFSET(::CEngineGotvSyncPacket, _impl_.instance_id_),
        PROTOBUF_FIELD_OFFSET(::CEngineGotvSyncPacket, _impl_.signupfragment_),
        PROTOBUF_FIELD_OFFSET(::CEngineGotvSyncPacket, _impl_.currentfragment_),
        PROTOBUF_FIELD_OFFSET(::CEngineGotvSyncPacket, _impl_.tickrate_),
        PROTOBUF_FIELD_OFFSET(::CEngineGotvSyncPacket, _impl_.tick_),
        PROTOBUF_FIELD_OFFSET(::CEngineGotvSyncPacket, _impl_.rtdelay_),
        PROTOBUF_FIELD_OFFSET(::CEngineGotvSyncPacket, _impl_.rcvage_),
        PROTOBUF_FIELD_OFFSET(::CEngineGotvSyncPacket, _impl_.keyframe_interval_),
        PROTOBUF_FIELD_OFFSET(::CEngineGotvSyncPacket, _impl_.cdndelay_),
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::CEngineGotvSyncPacket)},
};
static const ::_pbi::MessageGlobalsBase* PROTOBUF_NONNULL const
    file_message_globals[] = {
        &::CEngineGotvSyncPacket_globals_,
};
const char descriptor_table_protodef_engine_5fgcmessages_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\027engine_gcmessages.proto\032 google/protob"
    "uf/descriptor.proto\"\335\001\n\025CEngineGotvSyncP"
    "acket\022\020\n\010match_id\030\001 \001(\004\022\023\n\013instance_id\030\002"
    " \001(\r\022\026\n\016signupfragment\030\003 \001(\r\022\027\n\017currentf"
    "ragment\030\004 \001(\r\022\020\n\010tickrate\030\005 \001(\002\022\014\n\004tick\030"
    "\006 \001(\r\022\017\n\007rtdelay\030\010 \001(\002\022\016\n\006rcvage\030\t \001(\002\022\031"
    "\n\021keyframe_interval\030\n \001(\002\022\020\n\010cdndelay\030\013 "
    "\001(\r"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_engine_5fgcmessages_2eproto_deps[1] = {
        &::descriptor_table_google_2fprotobuf_2fdescriptor_2eproto,
};
static ::absl::once_flag descriptor_table_engine_5fgcmessages_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_engine_5fgcmessages_2eproto = {
    false,
    false,
    283,
    descriptor_table_protodef_engine_5fgcmessages_2eproto,
    "engine_gcmessages.proto",
    &descriptor_table_engine_5fgcmessages_2eproto_once,
    descriptor_table_engine_5fgcmessages_2eproto_deps,
    1,
    1,
    schemas,
    file_message_globals,
    TableStruct_engine_5fgcmessages_2eproto::offsets,
    file_level_enum_descriptors_engine_5fgcmessages_2eproto,
    file_level_service_descriptors_engine_5fgcmessages_2eproto,
};
// ===================================================================

CEngineGotvSyncPacket::CEngineGotvSyncPacket(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CEngineGotvSyncPacket_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CEngineGotvSyncPacket)
}
CEngineGotvSyncPacket::CEngineGotvSyncPacket(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CEngineGotvSyncPacket& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CEngineGotvSyncPacket_get_class_data()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE CEngineGotvSyncPacket::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void CEngineGotvSyncPacket::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, match_id_),
           0,
           offsetof(Impl_, cdndelay_) -
               offsetof(Impl_, match_id_) +
               sizeof(Impl_::cdndelay_));
}
CEngineGotvSyncPacket::~CEngineGotvSyncPacket() {
  // @@protoc_insertion_point(destructor:CEngineGotvSyncPacket)
  SharedDtor(*this);
}
inline void CEngineGotvSyncPacket::SharedDtor(MessageLite& self) {
  CEngineGotvSyncPacket& this_ = static_cast<CEngineGotvSyncPacket&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CEngineGotvSyncPacket_class_data_ =
        CEngineGotvSyncPacket::InternalGenerateClassData_(CEngineGotvSyncPacket_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CEngineGotvSyncPacket::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CEngineGotvSyncPacket_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CEngineGotvSyncPacket_class_data_.tc_table);
  return CEngineGotvSyncPacket_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CEngineGotvSyncPacket::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CEngineGotvSyncPacket_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&CEngineGotvSyncPacket_globals_));
  return CEngineGotvSyncPacket_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const CEngineGotvSyncPacket::ParseTableT_
    CEngineGotvSyncPacket::_table_ =
        CEngineGotvSyncPacket::InternalGenerateParseTable_(CEngineGotvSyncPacket_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void CEngineGotvSyncPacket::Clear() {
// @@protoc_insertion_point(message_clear_start:CEngineGotvSyncPacket)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    ::memset(&_impl_.match_id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.rcvage_) -
        reinterpret_cast<char*>(&_impl_.match_id_)) + sizeof(_impl_.rcvage_));
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000300U)) {
    ::memset(&_impl_.keyframe_interval_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.cdndelay_) -
        reinterpret_cast<char*>(&_impl_.keyframe_interval_)) + sizeof(_impl_.cdndelay_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CEngineGotvSyncPacket::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CEngineGotvSyncPacket& this_ = static_cast<const CEngineGotvSyncPacket&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CEngineGotvSyncPacket::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CEngineGotvSyncPacket& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:CEngineGotvSyncPacket)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional uint64 match_id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        1, this_._internal_match_id(), target);
  }

  // optional uint32 instance_id = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this_._internal_instance_id(), target);
  }

  // optional uint32 signupfragment = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        3, this_._internal_signupfragment(), target);
  }

  // optional uint32 currentfragment = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        4, this_._internal_currentfragment(), target);
  }

  // optional float tickrate = 5;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        5, this_._internal_tickrate(), target);
  }

  // optional uint32 tick = 6;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        6, this_._internal_tick(), target);
  }

  // optional float rtdelay = 8;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        8, this_._internal_rtdelay(), target);
  }

  // optional float rcvage = 9;
  if (CheckHasBit(cached_has_bits, 0x00000080U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        9, this_._internal_rcvage(), target);
  }

  // optional float keyframe_interval = 10;
  if (CheckHasBit(cached_has_bits, 0x00000100U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        10, this_._internal_keyframe_interval(), target);
  }

  // optional uint32 cdndelay = 11;
  if (CheckHasBit(cached_has_bits, 0x00000200U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        11, this_._internal_cdndelay(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CEngineGotvSyncPacket)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CEngineGotvSyncPacket::ByteSizeLong(const MessageLite& base) {
  const CEngineGotvSyncPacket& this_ = static_cast<const CEngineGotvSyncPacket&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CEngineGotvSyncPacket::ByteSizeLong() const {
  const CEngineGotvSyncPacket& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:CEngineGotvSyncPacket)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  total_size += ::absl::popcount(0x000001d0U & cached_has_bits) * 5;
  if (BatchCheckHasBit(cached_has_bits, 0x0000002fU)) {
    // optional uint64 match_id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
          this_._internal_match_id());
    }
    // optional uint32 instance_id = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_instance_id());
    }
    // optional uint32 signupfragment = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_signupfragment());
    }
    // optional uint32 currentfragment = 4;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_currentfragment());
    }
    // optional uint32 tick = 6;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_tick());
    }
  }
   {
    // optional uint32 cdndelay = 11;
    if (CheckHasBit(cached_has_bits, 0x00000200U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_cdndelay());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CEngineGotvSyncPacket::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<CEngineGotvSyncPacket*>(&to_msg);
  auto& from = static_cast<const CEngineGotvSyncPacket&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:CEngineGotvSyncPacket)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_impl_.match_id_ = from._impl_.match_id_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_impl_.instance_id_ = from._impl_.instance_id_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_impl_.signupfragment_ = from._impl_.signupfragment_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _this->_impl_.currentfragment_ = from._impl_.currentfragment_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _this->_impl_.tickrate_ = from._impl_.tickrate_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      _this->_impl_.tick_ = from._impl_.tick_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      _this->_impl_.rtdelay_ = from._impl_.rtdelay_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      _this->_impl_.rcvage_ = from._impl_.rcvage_;
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000300U)) {
    if (CheckHasBit(cached_has_bits, 0x00000100U)) {
      _this->_impl_.keyframe_interval_ = from._impl_.keyframe_interval_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000200U)) {
      _this->_impl_.cdndelay_ = from._impl_.cdndelay_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void CEngineGotvSyncPacket::CopyFrom(const CEngineGotvSyncPacket& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:CEngineGotvSyncPacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CEngineGotvSyncPacket::InternalSwap(CEngineGotvSyncPacket* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_.cdndelay_)
      + sizeof(CEngineGotvSyncPacket::_impl_.cdndelay_)
      - PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_.match_id_)>(
          reinterpret_cast<char*>(&_impl_.match_id_),
          reinterpret_cast<char*>(&other->_impl_.match_id_));
}

::google::protobuf::Metadata CEngineGotvSyncPacket::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_engine_5fgcmessages_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
