// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: networksystem_protomessages.proto
// Protobuf C++ Version: 7.35.1

#include "networksystem_protomessages.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
#ifdef PROTOBUF_MESSAGE_GLOBALS
namespace {
PROTOBUF_CONSTINIT ::google::protobuf::internal::ReflectionData
    file_reflection_data[] = {
        // ::NetMessageSplitscreenUserChanged
        {&::_pbi::kDescriptorMethods, &::descriptor_table_networksystem_5fprotomessages_2eproto, /* tracker*/ nullptr,},
        // ::NetMessageConnectionClosed
        {&::_pbi::kDescriptorMethods, &::descriptor_table_networksystem_5fprotomessages_2eproto, /* tracker*/ nullptr,},
        // ::NetMessageConnectionCrashed
        {&::_pbi::kDescriptorMethods, &::descriptor_table_networksystem_5fprotomessages_2eproto, /* tracker*/ nullptr,},
        // ::NetMessagePacketStart
        {&::_pbi::kDescriptorMethods, &::descriptor_table_networksystem_5fprotomessages_2eproto, /* tracker*/ nullptr,},
        // ::NetMessagePacketEnd
        {&::_pbi::kDescriptorMethods, &::descriptor_table_networksystem_5fprotomessages_2eproto, /* tracker*/ nullptr,},
};
}  // namespace
#endif
class NetMessageSplitscreenUserChanged::_Internal {
 public:
  using HasBits = decltype(::std::declval<NetMessageSplitscreenUserChanged>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(NetMessageSplitscreenUserChanged, _impl_._has_bits_);
};

constexpr NetMessageSplitscreenUserChanged::ParseTableT_ NetMessageSplitscreenUserChanged::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(NetMessageSplitscreenUserChanged, _impl_._has_bits_),
      0, // no _extensions_
      1, 0,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967294,  // skipmap
      offsetof(ParseTableT_, field_entries),
      1,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::NetMessageSplitscreenUserChanged>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      // optional uint32 slot = 1;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(NetMessageSplitscreenUserChanged, _impl_.slot_), 0>(),
       {8, 0, 0,
        PROTOBUF_FIELD_OFFSET(NetMessageSplitscreenUserChanged, _impl_.slot_)}},
    }}, {{
      65535, 65535
    }}, {{
      // optional uint32 slot = 1;
      {PROTOBUF_FIELD_OFFSET(NetMessageSplitscreenUserChanged, _impl_.slot_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    }},
    // no aux_entries
    {{
    }},
  };
}


inline constexpr NetMessageSplitscreenUserChanged::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        slot_{0u} {}

template <typename>
constexpr NetMessageSplitscreenUserChanged::NetMessageSplitscreenUserChanged(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::Message(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL NetMessageSplitscreenUserChanged::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) NetMessageSplitscreenUserChanged(arena);
}
constexpr auto NetMessageSplitscreenUserChanged::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(NetMessageSplitscreenUserChanged), alignof(NetMessageSplitscreenUserChanged));
}
constexpr auto NetMessageSplitscreenUserChanged::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &NetMessageSplitscreenUserChanged::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<NetMessageSplitscreenUserChanged>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &NetMessageSplitscreenUserChanged::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<NetMessageSplitscreenUserChanged>(), &NetMessageSplitscreenUserChanged::ByteSizeLong,
              &NetMessageSplitscreenUserChanged::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(NetMessageSplitscreenUserChanged, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[0],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_networksystem_5fprotomessages_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct NetMessageSplitscreenUserChangedGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr NetMessageSplitscreenUserChangedGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 NetMessageSplitscreenUserChanged_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(NetMessageSplitscreenUserChanged::InternalGenerateClassData_(
            _default, &NetMessageSplitscreenUserChanged_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<NetMessageSplitscreenUserChanged>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~NetMessageSplitscreenUserChangedGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) NetMessageSplitscreenUserChanged _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<NetMessageSplitscreenUserChanged>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(NetMessageSplitscreenUserChangedGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST NetMessageSplitscreenUserChangedGlobalsTypeInternal NetMessageSplitscreenUserChanged_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* NetMessageSplitscreenUserChanged_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return NetMessageSplitscreenUserChanged_globals_.GetClassData();
#else
  return NetMessageSplitscreenUserChanged_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
class NetMessagePacketStart::_Internal {
 public:
};

constexpr NetMessagePacketStart::ParseTableT_ NetMessagePacketStart::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(NetMessagePacketStart,
                            _impl_._cached_size_),  // no hasbits
      0, // no _extensions_
      0, 0,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967295,  // skipmap
      offsetof(ParseTableT_, field_names),  // no field_entries
      0,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::NetMessagePacketStart>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      {::_pbi::TcParser::MiniParse, {}},
    }}, {{
      65535, 65535
    }}, // no field_entries, or aux_entries
    {{
    }},
  };
}

template <typename>
constexpr NetMessagePacketStart::NetMessagePacketStart(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::internal::ZeroFieldsBase(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
      ) {
}
inline void* PROTOBUF_NONNULL NetMessagePacketStart::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) NetMessagePacketStart(arena);
}
constexpr auto NetMessagePacketStart::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(NetMessagePacketStart), alignof(NetMessagePacketStart));
}
constexpr auto NetMessagePacketStart::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &NetMessagePacketStart::MergeImpl,
          ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<NetMessagePacketStart>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &NetMessagePacketStart::SharedDtor,
          ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<NetMessagePacketStart>(), &NetMessagePacketStart::ByteSizeLong,
              &NetMessagePacketStart::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(NetMessagePacketStart, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[3],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_networksystem_5fprotomessages_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct NetMessagePacketStartGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr NetMessagePacketStartGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 NetMessagePacketStart_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(NetMessagePacketStart::InternalGenerateClassData_(
            _default, &NetMessagePacketStart_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<NetMessagePacketStart>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~NetMessagePacketStartGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) NetMessagePacketStart _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<NetMessagePacketStart>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(NetMessagePacketStartGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST NetMessagePacketStartGlobalsTypeInternal NetMessagePacketStart_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* NetMessagePacketStart_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return NetMessagePacketStart_globals_.GetClassData();
#else
  return NetMessagePacketStart_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
class NetMessagePacketEnd::_Internal {
 public:
};

constexpr NetMessagePacketEnd::ParseTableT_ NetMessagePacketEnd::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(NetMessagePacketEnd,
                            _impl_._cached_size_),  // no hasbits
      0, // no _extensions_
      0, 0,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967295,  // skipmap
      offsetof(ParseTableT_, field_names),  // no field_entries
      0,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::NetMessagePacketEnd>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      {::_pbi::TcParser::MiniParse, {}},
    }}, {{
      65535, 65535
    }}, // no field_entries, or aux_entries
    {{
    }},
  };
}

template <typename>
constexpr NetMessagePacketEnd::NetMessagePacketEnd(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::internal::ZeroFieldsBase(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
      ) {
}
inline void* PROTOBUF_NONNULL NetMessagePacketEnd::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) NetMessagePacketEnd(arena);
}
constexpr auto NetMessagePacketEnd::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(NetMessagePacketEnd), alignof(NetMessagePacketEnd));
}
constexpr auto NetMessagePacketEnd::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &NetMessagePacketEnd::MergeImpl,
          ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<NetMessagePacketEnd>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &NetMessagePacketEnd::SharedDtor,
          ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<NetMessagePacketEnd>(), &NetMessagePacketEnd::ByteSizeLong,
              &NetMessagePacketEnd::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(NetMessagePacketEnd, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[4],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_networksystem_5fprotomessages_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct NetMessagePacketEndGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr NetMessagePacketEndGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 NetMessagePacketEnd_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(NetMessagePacketEnd::InternalGenerateClassData_(
            _default, &NetMessagePacketEnd_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<NetMessagePacketEnd>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~NetMessagePacketEndGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) NetMessagePacketEnd _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<NetMessagePacketEnd>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(NetMessagePacketEndGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST NetMessagePacketEndGlobalsTypeInternal NetMessagePacketEnd_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* NetMessagePacketEnd_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return NetMessagePacketEnd_globals_.GetClassData();
#else
  return NetMessagePacketEnd_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
class NetMessageConnectionCrashed::_Internal {
 public:
  using HasBits = decltype(::std::declval<NetMessageConnectionCrashed>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(NetMessageConnectionCrashed, _impl_._has_bits_);
};

constexpr NetMessageConnectionCrashed::ParseTableT_ NetMessageConnectionCrashed::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(NetMessageConnectionCrashed, _impl_._has_bits_),
      0, // no _extensions_
      2, 8,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967292,  // skipmap
      offsetof(ParseTableT_, field_entries),
      2,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::NetMessageConnectionCrashed>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      // optional string message = 2;
      {::_pbi::TcParser::FastBS1,
       {18, 0, 0,
        PROTOBUF_FIELD_OFFSET(NetMessageConnectionCrashed, _impl_.message_)}},
      // optional uint32 reason = 1;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(NetMessageConnectionCrashed, _impl_.reason_), 1>(),
       {8, 1, 0,
        PROTOBUF_FIELD_OFFSET(NetMessageConnectionCrashed, _impl_.reason_)}},
    }}, {{
      65535, 65535
    }}, {{
      // optional uint32 reason = 1;
      {PROTOBUF_FIELD_OFFSET(NetMessageConnectionCrashed, _impl_.reason_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
      // optional string message = 2;
      {PROTOBUF_FIELD_OFFSET(NetMessageConnectionCrashed, _impl_.message_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    }},
    // no aux_entries
    {{
    }},
  };
}


inline constexpr NetMessageConnectionCrashed::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        reason_{0u} {}

template <typename>
constexpr NetMessageConnectionCrashed::NetMessageConnectionCrashed(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::Message(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL NetMessageConnectionCrashed::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) NetMessageConnectionCrashed(arena);
}
constexpr auto NetMessageConnectionCrashed::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(NetMessageConnectionCrashed), alignof(NetMessageConnectionCrashed));
}
constexpr auto NetMessageConnectionCrashed::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &NetMessageConnectionCrashed::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<NetMessageConnectionCrashed>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &NetMessageConnectionCrashed::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<NetMessageConnectionCrashed>(), &NetMessageConnectionCrashed::ByteSizeLong,
              &NetMessageConnectionCrashed::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(NetMessageConnectionCrashed, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[2],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_networksystem_5fprotomessages_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct NetMessageConnectionCrashedGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr NetMessageConnectionCrashedGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 NetMessageConnectionCrashed_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(NetMessageConnectionCrashed::InternalGenerateClassData_(
            _default, &NetMessageConnectionCrashed_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<NetMessageConnectionCrashed>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~NetMessageConnectionCrashedGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) NetMessageConnectionCrashed _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<NetMessageConnectionCrashed>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(NetMessageConnectionCrashedGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST NetMessageConnectionCrashedGlobalsTypeInternal NetMessageConnectionCrashed_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* NetMessageConnectionCrashed_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return NetMessageConnectionCrashed_globals_.GetClassData();
#else
  return NetMessageConnectionCrashed_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
class NetMessageConnectionClosed::_Internal {
 public:
  using HasBits = decltype(::std::declval<NetMessageConnectionClosed>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(NetMessageConnectionClosed, _impl_._has_bits_);
};

constexpr NetMessageConnectionClosed::ParseTableT_ NetMessageConnectionClosed::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(NetMessageConnectionClosed, _impl_._has_bits_),
      0, // no _extensions_
      2, 8,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967292,  // skipmap
      offsetof(ParseTableT_, field_entries),
      2,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::NetMessageConnectionClosed>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      // optional string message = 2;
      {::_pbi::TcParser::FastBS1,
       {18, 0, 0,
        PROTOBUF_FIELD_OFFSET(NetMessageConnectionClosed, _impl_.message_)}},
      // optional uint32 reason = 1;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(NetMessageConnectionClosed, _impl_.reason_), 1>(),
       {8, 1, 0,
        PROTOBUF_FIELD_OFFSET(NetMessageConnectionClosed, _impl_.reason_)}},
    }}, {{
      65535, 65535
    }}, {{
      // optional uint32 reason = 1;
      {PROTOBUF_FIELD_OFFSET(NetMessageConnectionClosed, _impl_.reason_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
      // optional string message = 2;
      {PROTOBUF_FIELD_OFFSET(NetMessageConnectionClosed, _impl_.message_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    }},
    // no aux_entries
    {{
    }},
  };
}


inline constexpr NetMessageConnectionClosed::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        reason_{0u} {}

template <typename>
constexpr NetMessageConnectionClosed::NetMessageConnectionClosed(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::Message(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL NetMessageConnectionClosed::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) NetMessageConnectionClosed(arena);
}
constexpr auto NetMessageConnectionClosed::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(NetMessageConnectionClosed), alignof(NetMessageConnectionClosed));
}
constexpr auto NetMessageConnectionClosed::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &NetMessageConnectionClosed::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<NetMessageConnectionClosed>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &NetMessageConnectionClosed::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<NetMessageConnectionClosed>(), &NetMessageConnectionClosed::ByteSizeLong,
              &NetMessageConnectionClosed::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(NetMessageConnectionClosed, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[1],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_networksystem_5fprotomessages_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct NetMessageConnectionClosedGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr NetMessageConnectionClosedGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 NetMessageConnectionClosed_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(NetMessageConnectionClosed::InternalGenerateClassData_(
            _default, &NetMessageConnectionClosed_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<NetMessageConnectionClosed>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~NetMessageConnectionClosedGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) NetMessageConnectionClosed _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<NetMessageConnectionClosed>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(NetMessageConnectionClosedGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST NetMessageConnectionClosedGlobalsTypeInternal NetMessageConnectionClosed_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* NetMessageConnectionClosed_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return NetMessageConnectionClosed_globals_.GetClassData();
#else
  return NetMessageConnectionClosed_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_networksystem_5fprotomessages_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_networksystem_5fprotomessages_2eproto = nullptr;
const ::uint32_t
    TableStruct_networksystem_5fprotomessages_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::NetMessageSplitscreenUserChanged, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::NetMessageSplitscreenUserChanged, _impl_.slot_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::NetMessageConnectionClosed, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::NetMessageConnectionClosed, _impl_.reason_),
        PROTOBUF_FIELD_OFFSET(::NetMessageConnectionClosed, _impl_.message_),
        1,
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::NetMessageConnectionCrashed, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::NetMessageConnectionCrashed, _impl_.reason_),
        PROTOBUF_FIELD_OFFSET(::NetMessageConnectionCrashed, _impl_.message_),
        1,
        0,
        0x000, // bitmap
        0x000, // bitmap
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::NetMessageSplitscreenUserChanged)},
        {5, sizeof(::NetMessageConnectionClosed)},
        {12, sizeof(::NetMessageConnectionCrashed)},
        {19, sizeof(::NetMessagePacketStart)},
        {20, sizeof(::NetMessagePacketEnd)},
};
static const ::_pbi::MessageGlobalsBase* PROTOBUF_NONNULL const
    file_message_globals[] = {
        &::NetMessageSplitscreenUserChanged_globals_,
        &::NetMessageConnectionClosed_globals_,
        &::NetMessageConnectionCrashed_globals_,
        &::NetMessagePacketStart_globals_,
        &::NetMessagePacketEnd_globals_,
};
const char descriptor_table_protodef_networksystem_5fprotomessages_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n!networksystem_protomessages.proto\"0\n N"
    "etMessageSplitscreenUserChanged\022\014\n\004slot\030"
    "\001 \001(\r\"=\n\032NetMessageConnectionClosed\022\016\n\006r"
    "eason\030\001 \001(\r\022\017\n\007message\030\002 \001(\t\">\n\033NetMessa"
    "geConnectionCrashed\022\016\n\006reason\030\001 \001(\r\022\017\n\007m"
    "essage\030\002 \001(\t\"\027\n\025NetMessagePacketStart\"\025\n"
    "\023NetMessagePacketEnd"
};
static ::absl::once_flag descriptor_table_networksystem_5fprotomessages_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_networksystem_5fprotomessages_2eproto = {
    false,
    false,
    260,
    descriptor_table_protodef_networksystem_5fprotomessages_2eproto,
    "networksystem_protomessages.proto",
    &descriptor_table_networksystem_5fprotomessages_2eproto_once,
    nullptr,
    0,
    5,
    schemas,
    file_message_globals,
    TableStruct_networksystem_5fprotomessages_2eproto::offsets,
    file_level_enum_descriptors_networksystem_5fprotomessages_2eproto,
    file_level_service_descriptors_networksystem_5fprotomessages_2eproto,
};
// ===================================================================

NetMessageSplitscreenUserChanged::NetMessageSplitscreenUserChanged(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, NetMessageSplitscreenUserChanged_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:NetMessageSplitscreenUserChanged)
}
NetMessageSplitscreenUserChanged::NetMessageSplitscreenUserChanged(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const NetMessageSplitscreenUserChanged& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, NetMessageSplitscreenUserChanged_get_class_data()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE NetMessageSplitscreenUserChanged::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void NetMessageSplitscreenUserChanged::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.slot_ = {};
}
NetMessageSplitscreenUserChanged::~NetMessageSplitscreenUserChanged() {
  // @@protoc_insertion_point(destructor:NetMessageSplitscreenUserChanged)
  SharedDtor(*this);
}
inline void NetMessageSplitscreenUserChanged::SharedDtor(MessageLite& self) {
  NetMessageSplitscreenUserChanged& this_ = static_cast<NetMessageSplitscreenUserChanged&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull NetMessageSplitscreenUserChanged_class_data_ =
        NetMessageSplitscreenUserChanged::InternalGenerateClassData_(NetMessageSplitscreenUserChanged_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
NetMessageSplitscreenUserChanged::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&NetMessageSplitscreenUserChanged_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(NetMessageSplitscreenUserChanged_class_data_.tc_table);
  return NetMessageSplitscreenUserChanged_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
NetMessageSplitscreenUserChanged::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&NetMessageSplitscreenUserChanged_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&NetMessageSplitscreenUserChanged_globals_));
  return NetMessageSplitscreenUserChanged_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const NetMessageSplitscreenUserChanged::ParseTableT_
    NetMessageSplitscreenUserChanged::_table_ =
        NetMessageSplitscreenUserChanged::InternalGenerateParseTable_(NetMessageSplitscreenUserChanged_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void NetMessageSplitscreenUserChanged::Clear() {
// @@protoc_insertion_point(message_clear_start:NetMessageSplitscreenUserChanged)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.slot_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL NetMessageSplitscreenUserChanged::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const NetMessageSplitscreenUserChanged& this_ = static_cast<const NetMessageSplitscreenUserChanged&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL NetMessageSplitscreenUserChanged::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const NetMessageSplitscreenUserChanged& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:NetMessageSplitscreenUserChanged)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional uint32 slot = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this_._internal_slot(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:NetMessageSplitscreenUserChanged)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t NetMessageSplitscreenUserChanged::ByteSizeLong(const MessageLite& base) {
  const NetMessageSplitscreenUserChanged& this_ = static_cast<const NetMessageSplitscreenUserChanged&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t NetMessageSplitscreenUserChanged::ByteSizeLong() const {
  const NetMessageSplitscreenUserChanged& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:NetMessageSplitscreenUserChanged)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // optional uint32 slot = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_slot());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void NetMessageSplitscreenUserChanged::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<NetMessageSplitscreenUserChanged*>(&to_msg);
  auto& from = static_cast<const NetMessageSplitscreenUserChanged&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:NetMessageSplitscreenUserChanged)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _this->_impl_.slot_ = from._impl_.slot_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void NetMessageSplitscreenUserChanged::CopyFrom(const NetMessageSplitscreenUserChanged& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:NetMessageSplitscreenUserChanged)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void NetMessageSplitscreenUserChanged::InternalSwap(NetMessageSplitscreenUserChanged* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.slot_, other->_impl_.slot_);
}

::google::protobuf::Metadata NetMessageSplitscreenUserChanged::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

NetMessageConnectionClosed::NetMessageConnectionClosed(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, NetMessageConnectionClosed_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:NetMessageConnectionClosed)
}
PROTOBUF_NDEBUG_INLINE NetMessageConnectionClosed::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::NetMessageConnectionClosed& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        message_(arena, from.message_) {}

NetMessageConnectionClosed::NetMessageConnectionClosed(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const NetMessageConnectionClosed& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, NetMessageConnectionClosed_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  NetMessageConnectionClosed* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.reason_ = from._impl_.reason_;

  // @@protoc_insertion_point(copy_constructor:NetMessageConnectionClosed)
}
PROTOBUF_NDEBUG_INLINE NetMessageConnectionClosed::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        message_(arena) {}

inline void NetMessageConnectionClosed::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.reason_ = {};
}
NetMessageConnectionClosed::~NetMessageConnectionClosed() {
  // @@protoc_insertion_point(destructor:NetMessageConnectionClosed)
  SharedDtor(*this);
}
inline void NetMessageConnectionClosed::SharedDtor(MessageLite& self) {
  NetMessageConnectionClosed& this_ = static_cast<NetMessageConnectionClosed&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.message_.Destroy();
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull NetMessageConnectionClosed_class_data_ =
        NetMessageConnectionClosed::InternalGenerateClassData_(NetMessageConnectionClosed_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
NetMessageConnectionClosed::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&NetMessageConnectionClosed_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(NetMessageConnectionClosed_class_data_.tc_table);
  return NetMessageConnectionClosed_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
NetMessageConnectionClosed::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&NetMessageConnectionClosed_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&NetMessageConnectionClosed_globals_));
  return NetMessageConnectionClosed_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const NetMessageConnectionClosed::ParseTableT_
    NetMessageConnectionClosed::_table_ =
        NetMessageConnectionClosed::InternalGenerateParseTable_(NetMessageConnectionClosed_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void NetMessageConnectionClosed::Clear() {
// @@protoc_insertion_point(message_clear_start:NetMessageConnectionClosed)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.message_.ClearNonDefaultToEmpty();
  }
  _impl_.reason_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL NetMessageConnectionClosed::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const NetMessageConnectionClosed& this_ = static_cast<const NetMessageConnectionClosed&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL NetMessageConnectionClosed::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const NetMessageConnectionClosed& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:NetMessageConnectionClosed)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional uint32 reason = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this_._internal_reason(), target);
  }

  // optional string message = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    const ::std::string& _s = this_._internal_message();
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:NetMessageConnectionClosed)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t NetMessageConnectionClosed::ByteSizeLong(const MessageLite& base) {
  const NetMessageConnectionClosed& this_ = static_cast<const NetMessageConnectionClosed&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t NetMessageConnectionClosed::ByteSizeLong() const {
  const NetMessageConnectionClosed& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:NetMessageConnectionClosed)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // optional string message = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_message());
    }
    // optional uint32 reason = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_reason());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void NetMessageConnectionClosed::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<NetMessageConnectionClosed*>(&to_msg);
  auto& from = static_cast<const NetMessageConnectionClosed&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:NetMessageConnectionClosed)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_set_message(from._internal_message());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_impl_.reason_ = from._impl_.reason_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void NetMessageConnectionClosed::CopyFrom(const NetMessageConnectionClosed& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:NetMessageConnectionClosed)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void NetMessageConnectionClosed::InternalSwap(NetMessageConnectionClosed* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
  swap(_impl_.reason_, other->_impl_.reason_);
}

::google::protobuf::Metadata NetMessageConnectionClosed::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

NetMessageConnectionCrashed::NetMessageConnectionCrashed(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, NetMessageConnectionCrashed_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:NetMessageConnectionCrashed)
}
PROTOBUF_NDEBUG_INLINE NetMessageConnectionCrashed::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::NetMessageConnectionCrashed& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        message_(arena, from.message_) {}

NetMessageConnectionCrashed::NetMessageConnectionCrashed(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const NetMessageConnectionCrashed& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, NetMessageConnectionCrashed_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  NetMessageConnectionCrashed* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.reason_ = from._impl_.reason_;

  // @@protoc_insertion_point(copy_constructor:NetMessageConnectionCrashed)
}
PROTOBUF_NDEBUG_INLINE NetMessageConnectionCrashed::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        message_(arena) {}

inline void NetMessageConnectionCrashed::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.reason_ = {};
}
NetMessageConnectionCrashed::~NetMessageConnectionCrashed() {
  // @@protoc_insertion_point(destructor:NetMessageConnectionCrashed)
  SharedDtor(*this);
}
inline void NetMessageConnectionCrashed::SharedDtor(MessageLite& self) {
  NetMessageConnectionCrashed& this_ = static_cast<NetMessageConnectionCrashed&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.message_.Destroy();
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull NetMessageConnectionCrashed_class_data_ =
        NetMessageConnectionCrashed::InternalGenerateClassData_(NetMessageConnectionCrashed_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
NetMessageConnectionCrashed::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&NetMessageConnectionCrashed_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(NetMessageConnectionCrashed_class_data_.tc_table);
  return NetMessageConnectionCrashed_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
NetMessageConnectionCrashed::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&NetMessageConnectionCrashed_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&NetMessageConnectionCrashed_globals_));
  return NetMessageConnectionCrashed_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const NetMessageConnectionCrashed::ParseTableT_
    NetMessageConnectionCrashed::_table_ =
        NetMessageConnectionCrashed::InternalGenerateParseTable_(NetMessageConnectionCrashed_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void NetMessageConnectionCrashed::Clear() {
// @@protoc_insertion_point(message_clear_start:NetMessageConnectionCrashed)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.message_.ClearNonDefaultToEmpty();
  }
  _impl_.reason_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL NetMessageConnectionCrashed::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const NetMessageConnectionCrashed& this_ = static_cast<const NetMessageConnectionCrashed&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL NetMessageConnectionCrashed::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const NetMessageConnectionCrashed& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:NetMessageConnectionCrashed)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional uint32 reason = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this_._internal_reason(), target);
  }

  // optional string message = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    const ::std::string& _s = this_._internal_message();
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:NetMessageConnectionCrashed)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t NetMessageConnectionCrashed::ByteSizeLong(const MessageLite& base) {
  const NetMessageConnectionCrashed& this_ = static_cast<const NetMessageConnectionCrashed&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t NetMessageConnectionCrashed::ByteSizeLong() const {
  const NetMessageConnectionCrashed& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:NetMessageConnectionCrashed)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // optional string message = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_message());
    }
    // optional uint32 reason = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_reason());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void NetMessageConnectionCrashed::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<NetMessageConnectionCrashed*>(&to_msg);
  auto& from = static_cast<const NetMessageConnectionCrashed&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:NetMessageConnectionCrashed)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_set_message(from._internal_message());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_impl_.reason_ = from._impl_.reason_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void NetMessageConnectionCrashed::CopyFrom(const NetMessageConnectionCrashed& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:NetMessageConnectionCrashed)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void NetMessageConnectionCrashed::InternalSwap(NetMessageConnectionCrashed* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
  swap(_impl_.reason_, other->_impl_.reason_);
}

::google::protobuf::Metadata NetMessageConnectionCrashed::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

NetMessagePacketStart::NetMessagePacketStart(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, NetMessagePacketStart_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:NetMessagePacketStart)
}
NetMessagePacketStart::NetMessagePacketStart(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const NetMessagePacketStart& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, NetMessagePacketStart_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  NetMessagePacketStart* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:NetMessagePacketStart)
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull NetMessagePacketStart_class_data_ =
        NetMessagePacketStart::InternalGenerateClassData_(NetMessagePacketStart_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
NetMessagePacketStart::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&NetMessagePacketStart_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(NetMessagePacketStart_class_data_.tc_table);
  return NetMessagePacketStart_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
NetMessagePacketStart::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&NetMessagePacketStart_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&NetMessagePacketStart_globals_));
  return NetMessagePacketStart_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const NetMessagePacketStart::ParseTableT_
    NetMessagePacketStart::_table_ =
        NetMessagePacketStart::InternalGenerateParseTable_(NetMessagePacketStart_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS







::google::protobuf::Metadata NetMessagePacketStart::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

NetMessagePacketEnd::NetMessagePacketEnd(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, NetMessagePacketEnd_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:NetMessagePacketEnd)
}
NetMessagePacketEnd::NetMessagePacketEnd(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const NetMessagePacketEnd& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, NetMessagePacketEnd_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  NetMessagePacketEnd* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:NetMessagePacketEnd)
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull NetMessagePacketEnd_class_data_ =
        NetMessagePacketEnd::InternalGenerateClassData_(NetMessagePacketEnd_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
NetMessagePacketEnd::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&NetMessagePacketEnd_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(NetMessagePacketEnd_class_data_.tc_table);
  return NetMessagePacketEnd_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
NetMessagePacketEnd::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&NetMessagePacketEnd_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&NetMessagePacketEnd_globals_));
  return NetMessagePacketEnd_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const NetMessagePacketEnd::ParseTableT_
    NetMessagePacketEnd::_table_ =
        NetMessagePacketEnd::InternalGenerateParseTable_(NetMessagePacketEnd_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS







::google::protobuf::Metadata NetMessagePacketEnd::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_networksystem_5fprotomessages_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
