// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: steammessages_helprequest.steamworkssdk.proto
// Protobuf C++ Version: 7.35.1

#include "steammessages_helprequest.steamworkssdk.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
#ifdef PROTOBUF_MESSAGE_GLOBALS
namespace {
PROTOBUF_CONSTINIT ::google::protobuf::internal::ReflectionData
    file_reflection_data[] = {
        // ::CHelpRequestLogs_UploadUserApplicationLog_Request
        {&::_pbi::kDescriptorMethods, &::descriptor_table_steammessages_5fhelprequest_2esteamworkssdk_2eproto, /* tracker*/ nullptr,},
        // ::CHelpRequestLogs_UploadUserApplicationLog_Response
        {&::_pbi::kDescriptorMethods, &::descriptor_table_steammessages_5fhelprequest_2esteamworkssdk_2eproto, /* tracker*/ nullptr,},
};
}  // namespace
#endif
class CHelpRequestLogs_UploadUserApplicationLog_Response::_Internal {
 public:
  using HasBits = decltype(::std::declval<CHelpRequestLogs_UploadUserApplicationLog_Response>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CHelpRequestLogs_UploadUserApplicationLog_Response, _impl_._has_bits_);
};

constexpr CHelpRequestLogs_UploadUserApplicationLog_Response::ParseTableT_ CHelpRequestLogs_UploadUserApplicationLog_Response::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(CHelpRequestLogs_UploadUserApplicationLog_Response, _impl_._has_bits_),
      0, // no _extensions_
      1, 0,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967294,  // skipmap
      offsetof(ParseTableT_, field_entries),
      1,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::CHelpRequestLogs_UploadUserApplicationLog_Response>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      // optional uint64 id = 1;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CHelpRequestLogs_UploadUserApplicationLog_Response, _impl_.id_), 0>(),
       {8, 0, 0,
        PROTOBUF_FIELD_OFFSET(CHelpRequestLogs_UploadUserApplicationLog_Response, _impl_.id_)}},
    }}, {{
      65535, 65535
    }}, {{
      // optional uint64 id = 1;
      {PROTOBUF_FIELD_OFFSET(CHelpRequestLogs_UploadUserApplicationLog_Response, _impl_.id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    }},
    // no aux_entries
    {{
    }},
  };
}


inline constexpr CHelpRequestLogs_UploadUserApplicationLog_Response::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        id_{::uint64_t{0u}} {}

template <typename>
constexpr CHelpRequestLogs_UploadUserApplicationLog_Response::CHelpRequestLogs_UploadUserApplicationLog_Response(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::Message(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL CHelpRequestLogs_UploadUserApplicationLog_Response::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CHelpRequestLogs_UploadUserApplicationLog_Response(arena);
}
constexpr auto CHelpRequestLogs_UploadUserApplicationLog_Response::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(CHelpRequestLogs_UploadUserApplicationLog_Response), alignof(CHelpRequestLogs_UploadUserApplicationLog_Response));
}
constexpr auto CHelpRequestLogs_UploadUserApplicationLog_Response::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &CHelpRequestLogs_UploadUserApplicationLog_Response::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CHelpRequestLogs_UploadUserApplicationLog_Response>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CHelpRequestLogs_UploadUserApplicationLog_Response::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CHelpRequestLogs_UploadUserApplicationLog_Response>(), &CHelpRequestLogs_UploadUserApplicationLog_Response::ByteSizeLong,
              &CHelpRequestLogs_UploadUserApplicationLog_Response::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CHelpRequestLogs_UploadUserApplicationLog_Response, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[1],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_steammessages_5fhelprequest_2esteamworkssdk_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct CHelpRequestLogs_UploadUserApplicationLog_ResponseGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr CHelpRequestLogs_UploadUserApplicationLog_ResponseGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 CHelpRequestLogs_UploadUserApplicationLog_Response_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(CHelpRequestLogs_UploadUserApplicationLog_Response::InternalGenerateClassData_(
            _default, &CHelpRequestLogs_UploadUserApplicationLog_Response_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<CHelpRequestLogs_UploadUserApplicationLog_Response>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~CHelpRequestLogs_UploadUserApplicationLog_ResponseGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) CHelpRequestLogs_UploadUserApplicationLog_Response _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<CHelpRequestLogs_UploadUserApplicationLog_Response>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(CHelpRequestLogs_UploadUserApplicationLog_ResponseGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST CHelpRequestLogs_UploadUserApplicationLog_ResponseGlobalsTypeInternal CHelpRequestLogs_UploadUserApplicationLog_Response_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* CHelpRequestLogs_UploadUserApplicationLog_Response_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return CHelpRequestLogs_UploadUserApplicationLog_Response_globals_.GetClassData();
#else
  return CHelpRequestLogs_UploadUserApplicationLog_Response_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
class CHelpRequestLogs_UploadUserApplicationLog_Request::_Internal {
 public:
  using HasBits = decltype(::std::declval<CHelpRequestLogs_UploadUserApplicationLog_Request>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CHelpRequestLogs_UploadUserApplicationLog_Request, _impl_._has_bits_);
};

constexpr CHelpRequestLogs_UploadUserApplicationLog_Request::ParseTableT_ CHelpRequestLogs_UploadUserApplicationLog_Request::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(CHelpRequestLogs_UploadUserApplicationLog_Request, _impl_._has_bits_),
      0, // no _extensions_
      4, 24,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967280,  // skipmap
      offsetof(ParseTableT_, field_entries),
      4,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::CHelpRequestLogs_UploadUserApplicationLog_Request>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      // optional string log_contents = 4;
      {::_pbi::TcParser::FastBS1,
       {34, 2, 0,
        PROTOBUF_FIELD_OFFSET(CHelpRequestLogs_UploadUserApplicationLog_Request, _impl_.log_contents_)}},
      // optional uint32 appid = 1;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CHelpRequestLogs_UploadUserApplicationLog_Request, _impl_.appid_), 3>(),
       {8, 3, 0,
        PROTOBUF_FIELD_OFFSET(CHelpRequestLogs_UploadUserApplicationLog_Request, _impl_.appid_)}},
      // optional string log_type = 2;
      {::_pbi::TcParser::FastBS1,
       {18, 0, 0,
        PROTOBUF_FIELD_OFFSET(CHelpRequestLogs_UploadUserApplicationLog_Request, _impl_.log_type_)}},
      // optional string version_string = 3;
      {::_pbi::TcParser::FastBS1,
       {26, 1, 0,
        PROTOBUF_FIELD_OFFSET(CHelpRequestLogs_UploadUserApplicationLog_Request, _impl_.version_string_)}},
    }}, {{
      65535, 65535
    }}, {{
      // optional uint32 appid = 1;
      {PROTOBUF_FIELD_OFFSET(CHelpRequestLogs_UploadUserApplicationLog_Request, _impl_.appid_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
      // optional string log_type = 2;
      {PROTOBUF_FIELD_OFFSET(CHelpRequestLogs_UploadUserApplicationLog_Request, _impl_.log_type_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
      // optional string version_string = 3;
      {PROTOBUF_FIELD_OFFSET(CHelpRequestLogs_UploadUserApplicationLog_Request, _impl_.version_string_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
      // optional string log_contents = 4;
      {PROTOBUF_FIELD_OFFSET(CHelpRequestLogs_UploadUserApplicationLog_Request, _impl_.log_contents_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    }},
    // no aux_entries
    {{
    }},
  };
}


inline constexpr CHelpRequestLogs_UploadUserApplicationLog_Request::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        log_type_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        version_string_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        log_contents_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        appid_{0u} {}

template <typename>
constexpr CHelpRequestLogs_UploadUserApplicationLog_Request::CHelpRequestLogs_UploadUserApplicationLog_Request(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::Message(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL CHelpRequestLogs_UploadUserApplicationLog_Request::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CHelpRequestLogs_UploadUserApplicationLog_Request(arena);
}
constexpr auto CHelpRequestLogs_UploadUserApplicationLog_Request::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(CHelpRequestLogs_UploadUserApplicationLog_Request), alignof(CHelpRequestLogs_UploadUserApplicationLog_Request));
}
constexpr auto CHelpRequestLogs_UploadUserApplicationLog_Request::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &CHelpRequestLogs_UploadUserApplicationLog_Request::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CHelpRequestLogs_UploadUserApplicationLog_Request>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CHelpRequestLogs_UploadUserApplicationLog_Request::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CHelpRequestLogs_UploadUserApplicationLog_Request>(), &CHelpRequestLogs_UploadUserApplicationLog_Request::ByteSizeLong,
              &CHelpRequestLogs_UploadUserApplicationLog_Request::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CHelpRequestLogs_UploadUserApplicationLog_Request, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[0],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_steammessages_5fhelprequest_2esteamworkssdk_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct CHelpRequestLogs_UploadUserApplicationLog_RequestGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr CHelpRequestLogs_UploadUserApplicationLog_RequestGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 CHelpRequestLogs_UploadUserApplicationLog_Request_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(CHelpRequestLogs_UploadUserApplicationLog_Request::InternalGenerateClassData_(
            _default, &CHelpRequestLogs_UploadUserApplicationLog_Request_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<CHelpRequestLogs_UploadUserApplicationLog_Request>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~CHelpRequestLogs_UploadUserApplicationLog_RequestGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) CHelpRequestLogs_UploadUserApplicationLog_Request _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<CHelpRequestLogs_UploadUserApplicationLog_Request>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(CHelpRequestLogs_UploadUserApplicationLog_RequestGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST CHelpRequestLogs_UploadUserApplicationLog_RequestGlobalsTypeInternal CHelpRequestLogs_UploadUserApplicationLog_Request_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* CHelpRequestLogs_UploadUserApplicationLog_Request_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return CHelpRequestLogs_UploadUserApplicationLog_Request_globals_.GetClassData();
#else
  return CHelpRequestLogs_UploadUserApplicationLog_Request_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_steammessages_5fhelprequest_2esteamworkssdk_2eproto = nullptr;
static const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL
    file_level_service_descriptors_steammessages_5fhelprequest_2esteamworkssdk_2eproto[1];
const ::uint32_t
    TableStruct_steammessages_5fhelprequest_2esteamworkssdk_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::CHelpRequestLogs_UploadUserApplicationLog_Request, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::CHelpRequestLogs_UploadUserApplicationLog_Request, _impl_.appid_),
        PROTOBUF_FIELD_OFFSET(::CHelpRequestLogs_UploadUserApplicationLog_Request, _impl_.log_type_),
        PROTOBUF_FIELD_OFFSET(::CHelpRequestLogs_UploadUserApplicationLog_Request, _impl_.version_string_),
        PROTOBUF_FIELD_OFFSET(::CHelpRequestLogs_UploadUserApplicationLog_Request, _impl_.log_contents_),
        3,
        0,
        1,
        2,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::CHelpRequestLogs_UploadUserApplicationLog_Response, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::CHelpRequestLogs_UploadUserApplicationLog_Response, _impl_.id_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::CHelpRequestLogs_UploadUserApplicationLog_Request)},
        {11, sizeof(::CHelpRequestLogs_UploadUserApplicationLog_Response)},
};
static const ::_pbi::MessageGlobalsBase* PROTOBUF_NONNULL const
    file_message_globals[] = {
        &::CHelpRequestLogs_UploadUserApplicationLog_Request_globals_,
        &::CHelpRequestLogs_UploadUserApplicationLog_Response_globals_,
};
const char descriptor_table_protodef_steammessages_5fhelprequest_2esteamworkssdk_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n-steammessages_helprequest.steamworkssd"
    "k.proto\032.steammessages_unified_base.stea"
    "mworkssdk.proto\"\202\001\n1CHelpRequestLogs_Upl"
    "oadUserApplicationLog_Request\022\r\n\005appid\030\001"
    " \001(\r\022\020\n\010log_type\030\002 \001(\t\022\026\n\016version_string"
    "\030\003 \001(\t\022\024\n\014log_contents\030\004 \001(\t\"@\n2CHelpReq"
    "uestLogs_UploadUserApplicationLog_Respon"
    "se\022\n\n\002id\030\001 \001(\0042\356\001\n\017HelpRequestLogs\022\250\001\n\030U"
    "ploadUserApplicationLog\0222.CHelpRequestLo"
    "gs_UploadUserApplicationLog_Request\0323.CH"
    "elpRequestLogs_UploadUserApplicationLog_"
    "Response\"#\202\265\030\037User uploading application"
    " logs\0320\202\265\030,Service for dealing with user"
    "-submitted logsB\003\200\001\001"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_steammessages_5fhelprequest_2esteamworkssdk_2eproto_deps[1] = {
        &::descriptor_table_steammessages_5funified_5fbase_2esteamworkssdk_2eproto,
};
static ::absl::once_flag descriptor_table_steammessages_5fhelprequest_2esteamworkssdk_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_steammessages_5fhelprequest_2esteamworkssdk_2eproto = {
    false,
    false,
    540,
    descriptor_table_protodef_steammessages_5fhelprequest_2esteamworkssdk_2eproto,
    "steammessages_helprequest.steamworkssdk.proto",
    &descriptor_table_steammessages_5fhelprequest_2esteamworkssdk_2eproto_once,
    descriptor_table_steammessages_5fhelprequest_2esteamworkssdk_2eproto_deps,
    1,
    2,
    schemas,
    file_message_globals,
    TableStruct_steammessages_5fhelprequest_2esteamworkssdk_2eproto::offsets,
    file_level_enum_descriptors_steammessages_5fhelprequest_2esteamworkssdk_2eproto,
    file_level_service_descriptors_steammessages_5fhelprequest_2esteamworkssdk_2eproto,
};
// ===================================================================

CHelpRequestLogs_UploadUserApplicationLog_Request::CHelpRequestLogs_UploadUserApplicationLog_Request(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CHelpRequestLogs_UploadUserApplicationLog_Request_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CHelpRequestLogs_UploadUserApplicationLog_Request)
}
PROTOBUF_NDEBUG_INLINE CHelpRequestLogs_UploadUserApplicationLog_Request::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::CHelpRequestLogs_UploadUserApplicationLog_Request& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        log_type_(arena, from.log_type_),
        version_string_(arena, from.version_string_),
        log_contents_(arena, from.log_contents_) {}

CHelpRequestLogs_UploadUserApplicationLog_Request::CHelpRequestLogs_UploadUserApplicationLog_Request(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CHelpRequestLogs_UploadUserApplicationLog_Request& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CHelpRequestLogs_UploadUserApplicationLog_Request_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CHelpRequestLogs_UploadUserApplicationLog_Request* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.appid_ = from._impl_.appid_;

  // @@protoc_insertion_point(copy_constructor:CHelpRequestLogs_UploadUserApplicationLog_Request)
}
PROTOBUF_NDEBUG_INLINE CHelpRequestLogs_UploadUserApplicationLog_Request::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        log_type_(arena),
        version_string_(arena),
        log_contents_(arena) {}

inline void CHelpRequestLogs_UploadUserApplicationLog_Request::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.appid_ = {};
}
CHelpRequestLogs_UploadUserApplicationLog_Request::~CHelpRequestLogs_UploadUserApplicationLog_Request() {
  // @@protoc_insertion_point(destructor:CHelpRequestLogs_UploadUserApplicationLog_Request)
  SharedDtor(*this);
}
inline void CHelpRequestLogs_UploadUserApplicationLog_Request::SharedDtor(MessageLite& self) {
  CHelpRequestLogs_UploadUserApplicationLog_Request& this_ = static_cast<CHelpRequestLogs_UploadUserApplicationLog_Request&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.log_type_.Destroy();
  this_._impl_.version_string_.Destroy();
  this_._impl_.log_contents_.Destroy();
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CHelpRequestLogs_UploadUserApplicationLog_Request_class_data_ =
        CHelpRequestLogs_UploadUserApplicationLog_Request::InternalGenerateClassData_(CHelpRequestLogs_UploadUserApplicationLog_Request_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CHelpRequestLogs_UploadUserApplicationLog_Request::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CHelpRequestLogs_UploadUserApplicationLog_Request_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CHelpRequestLogs_UploadUserApplicationLog_Request_class_data_.tc_table);
  return CHelpRequestLogs_UploadUserApplicationLog_Request_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CHelpRequestLogs_UploadUserApplicationLog_Request::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CHelpRequestLogs_UploadUserApplicationLog_Request_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&CHelpRequestLogs_UploadUserApplicationLog_Request_globals_));
  return CHelpRequestLogs_UploadUserApplicationLog_Request_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const CHelpRequestLogs_UploadUserApplicationLog_Request::ParseTableT_
    CHelpRequestLogs_UploadUserApplicationLog_Request::_table_ =
        CHelpRequestLogs_UploadUserApplicationLog_Request::InternalGenerateParseTable_(CHelpRequestLogs_UploadUserApplicationLog_Request_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void CHelpRequestLogs_UploadUserApplicationLog_Request::Clear() {
// @@protoc_insertion_point(message_clear_start:CHelpRequestLogs_UploadUserApplicationLog_Request)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.log_type_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.version_string_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.log_contents_.ClearNonDefaultToEmpty();
    }
  }
  _impl_.appid_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CHelpRequestLogs_UploadUserApplicationLog_Request::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CHelpRequestLogs_UploadUserApplicationLog_Request& this_ = static_cast<const CHelpRequestLogs_UploadUserApplicationLog_Request&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CHelpRequestLogs_UploadUserApplicationLog_Request::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CHelpRequestLogs_UploadUserApplicationLog_Request& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:CHelpRequestLogs_UploadUserApplicationLog_Request)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional uint32 appid = 1;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this_._internal_appid(), target);
  }

  // optional string log_type = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    const ::std::string& _s = this_._internal_log_type();
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // optional string version_string = 3;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    const ::std::string& _s = this_._internal_version_string();
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // optional string log_contents = 4;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    const ::std::string& _s = this_._internal_log_contents();
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CHelpRequestLogs_UploadUserApplicationLog_Request)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CHelpRequestLogs_UploadUserApplicationLog_Request::ByteSizeLong(const MessageLite& base) {
  const CHelpRequestLogs_UploadUserApplicationLog_Request& this_ = static_cast<const CHelpRequestLogs_UploadUserApplicationLog_Request&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CHelpRequestLogs_UploadUserApplicationLog_Request::ByteSizeLong() const {
  const CHelpRequestLogs_UploadUserApplicationLog_Request& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:CHelpRequestLogs_UploadUserApplicationLog_Request)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    // optional string log_type = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_log_type());
    }
    // optional string version_string = 3;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_version_string());
    }
    // optional string log_contents = 4;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_log_contents());
    }
    // optional uint32 appid = 1;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_appid());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CHelpRequestLogs_UploadUserApplicationLog_Request::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<CHelpRequestLogs_UploadUserApplicationLog_Request*>(&to_msg);
  auto& from = static_cast<const CHelpRequestLogs_UploadUserApplicationLog_Request&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:CHelpRequestLogs_UploadUserApplicationLog_Request)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_set_log_type(from._internal_log_type());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_internal_set_version_string(from._internal_version_string());
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_internal_set_log_contents(from._internal_log_contents());
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _this->_impl_.appid_ = from._impl_.appid_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void CHelpRequestLogs_UploadUserApplicationLog_Request::CopyFrom(const CHelpRequestLogs_UploadUserApplicationLog_Request& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:CHelpRequestLogs_UploadUserApplicationLog_Request)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CHelpRequestLogs_UploadUserApplicationLog_Request::InternalSwap(CHelpRequestLogs_UploadUserApplicationLog_Request* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.log_type_, &other->_impl_.log_type_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.version_string_, &other->_impl_.version_string_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.log_contents_, &other->_impl_.log_contents_, arena);
  swap(_impl_.appid_, other->_impl_.appid_);
}

::google::protobuf::Metadata CHelpRequestLogs_UploadUserApplicationLog_Request::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

CHelpRequestLogs_UploadUserApplicationLog_Response::CHelpRequestLogs_UploadUserApplicationLog_Response(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CHelpRequestLogs_UploadUserApplicationLog_Response_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CHelpRequestLogs_UploadUserApplicationLog_Response)
}
CHelpRequestLogs_UploadUserApplicationLog_Response::CHelpRequestLogs_UploadUserApplicationLog_Response(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CHelpRequestLogs_UploadUserApplicationLog_Response& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CHelpRequestLogs_UploadUserApplicationLog_Response_get_class_data()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE CHelpRequestLogs_UploadUserApplicationLog_Response::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void CHelpRequestLogs_UploadUserApplicationLog_Response::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.id_ = {};
}
CHelpRequestLogs_UploadUserApplicationLog_Response::~CHelpRequestLogs_UploadUserApplicationLog_Response() {
  // @@protoc_insertion_point(destructor:CHelpRequestLogs_UploadUserApplicationLog_Response)
  SharedDtor(*this);
}
inline void CHelpRequestLogs_UploadUserApplicationLog_Response::SharedDtor(MessageLite& self) {
  CHelpRequestLogs_UploadUserApplicationLog_Response& this_ = static_cast<CHelpRequestLogs_UploadUserApplicationLog_Response&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CHelpRequestLogs_UploadUserApplicationLog_Response_class_data_ =
        CHelpRequestLogs_UploadUserApplicationLog_Response::InternalGenerateClassData_(CHelpRequestLogs_UploadUserApplicationLog_Response_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CHelpRequestLogs_UploadUserApplicationLog_Response::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CHelpRequestLogs_UploadUserApplicationLog_Response_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CHelpRequestLogs_UploadUserApplicationLog_Response_class_data_.tc_table);
  return CHelpRequestLogs_UploadUserApplicationLog_Response_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CHelpRequestLogs_UploadUserApplicationLog_Response::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CHelpRequestLogs_UploadUserApplicationLog_Response_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&CHelpRequestLogs_UploadUserApplicationLog_Response_globals_));
  return CHelpRequestLogs_UploadUserApplicationLog_Response_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const CHelpRequestLogs_UploadUserApplicationLog_Response::ParseTableT_
    CHelpRequestLogs_UploadUserApplicationLog_Response::_table_ =
        CHelpRequestLogs_UploadUserApplicationLog_Response::InternalGenerateParseTable_(CHelpRequestLogs_UploadUserApplicationLog_Response_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void CHelpRequestLogs_UploadUserApplicationLog_Response::Clear() {
// @@protoc_insertion_point(message_clear_start:CHelpRequestLogs_UploadUserApplicationLog_Response)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.id_ = ::uint64_t{0u};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CHelpRequestLogs_UploadUserApplicationLog_Response::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CHelpRequestLogs_UploadUserApplicationLog_Response& this_ = static_cast<const CHelpRequestLogs_UploadUserApplicationLog_Response&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CHelpRequestLogs_UploadUserApplicationLog_Response::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CHelpRequestLogs_UploadUserApplicationLog_Response& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:CHelpRequestLogs_UploadUserApplicationLog_Response)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional uint64 id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        1, this_._internal_id(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CHelpRequestLogs_UploadUserApplicationLog_Response)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CHelpRequestLogs_UploadUserApplicationLog_Response::ByteSizeLong(const MessageLite& base) {
  const CHelpRequestLogs_UploadUserApplicationLog_Response& this_ = static_cast<const CHelpRequestLogs_UploadUserApplicationLog_Response&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CHelpRequestLogs_UploadUserApplicationLog_Response::ByteSizeLong() const {
  const CHelpRequestLogs_UploadUserApplicationLog_Response& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:CHelpRequestLogs_UploadUserApplicationLog_Response)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // optional uint64 id = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
          this_._internal_id());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CHelpRequestLogs_UploadUserApplicationLog_Response::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<CHelpRequestLogs_UploadUserApplicationLog_Response*>(&to_msg);
  auto& from = static_cast<const CHelpRequestLogs_UploadUserApplicationLog_Response&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:CHelpRequestLogs_UploadUserApplicationLog_Response)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _this->_impl_.id_ = from._impl_.id_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void CHelpRequestLogs_UploadUserApplicationLog_Response::CopyFrom(const CHelpRequestLogs_UploadUserApplicationLog_Response& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:CHelpRequestLogs_UploadUserApplicationLog_Response)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CHelpRequestLogs_UploadUserApplicationLog_Response::InternalSwap(CHelpRequestLogs_UploadUserApplicationLog_Response* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.id_, other->_impl_.id_);
}

::google::protobuf::Metadata CHelpRequestLogs_UploadUserApplicationLog_Response::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

const ::google::protobuf::ServiceDescriptor* PROTOBUF_NONNULL HelpRequestLogs::descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_steammessages_5fhelprequest_2esteamworkssdk_2eproto);
  return file_level_service_descriptors_steammessages_5fhelprequest_2esteamworkssdk_2eproto[0];
}

const ::google::protobuf::ServiceDescriptor* PROTOBUF_NONNULL HelpRequestLogs::GetDescriptor() {
  return descriptor();
}

void HelpRequestLogs::UploadUserApplicationLog(::google::protobuf::RpcController* PROTOBUF_NULLABLE controller,
                         const ::CHelpRequestLogs_UploadUserApplicationLog_Request* PROTOBUF_NONNULL,
                         ::CHelpRequestLogs_UploadUserApplicationLog_Response* PROTOBUF_NONNULL,
                         ::google::protobuf::Closure* PROTOBUF_NULLABLE done) {
  controller->SetFailed("Method UploadUserApplicationLog() not implemented.");
  done->Run();
}

void HelpRequestLogs::CallMethod(
    const ::google::protobuf::MethodDescriptor* PROTOBUF_NONNULL method,
    ::google::protobuf::RpcController* PROTOBUF_NULLABLE controller,
    const ::google::protobuf::Message* PROTOBUF_NONNULL request,
    ::google::protobuf::Message* PROTOBUF_NONNULL response, ::google::protobuf::Closure* PROTOBUF_NULLABLE done) {
  ABSL_DCHECK_EQ(method->service(), file_level_service_descriptors_steammessages_5fhelprequest_2esteamworkssdk_2eproto[0]);
  switch (method->index()) {
    case 0:
      this->UploadUserApplicationLog(controller, ::google::protobuf::DownCastMessage<::CHelpRequestLogs_UploadUserApplicationLog_Request>(request),
                   ::google::protobuf::DownCastMessage<::CHelpRequestLogs_UploadUserApplicationLog_Response>(response), done);
      break;

    default:
      ABSL_LOG(FATAL) << "Bad method index; this should never happen.";
      break;
  }
}

const ::google::protobuf::Message& HelpRequestLogs::GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* PROTOBUF_NONNULL method) const {
  ABSL_DCHECK_EQ(method->service(), descriptor());
  switch (method->index()) {
    case 0:
      return ::CHelpRequestLogs_UploadUserApplicationLog_Request::default_instance();

    default:
      ABSL_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::google::protobuf::MessageFactory::generated_factory()->GetPrototype(
          method->input_type());
  }
}

const ::google::protobuf::Message& HelpRequestLogs::GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* PROTOBUF_NONNULL method) const {
  ABSL_DCHECK_EQ(method->service(), descriptor());
  switch (method->index()) {
    case 0:
      return ::CHelpRequestLogs_UploadUserApplicationLog_Response::default_instance();

    default:
      ABSL_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::google::protobuf::MessageFactory::generated_factory()->GetPrototype(
          method->output_type());
  }
}

HelpRequestLogs_Stub::HelpRequestLogs_Stub(::google::protobuf::RpcChannel* PROTOBUF_NULLABLE channel)
    : channel_(channel), owns_channel_(false) {}

HelpRequestLogs_Stub::HelpRequestLogs_Stub(
    ::google::protobuf::RpcChannel* PROTOBUF_NULLABLE channel,
    ::google::protobuf::Service::ChannelOwnership ownership)
    : channel_(channel),
      owns_channel_(ownership == ::google::protobuf::Service::STUB_OWNS_CHANNEL) {}

HelpRequestLogs_Stub::~HelpRequestLogs_Stub() {
  if (owns_channel_) delete channel_;
}

void HelpRequestLogs_Stub::UploadUserApplicationLog(
    ::google::protobuf::RpcController* PROTOBUF_NULLABLE controller,
    const ::CHelpRequestLogs_UploadUserApplicationLog_Request* PROTOBUF_NONNULL request, ::CHelpRequestLogs_UploadUserApplicationLog_Response* PROTOBUF_NONNULL response,
    ::google::protobuf::Closure* PROTOBUF_NULLABLE done) {
  channel_->CallMethod(descriptor()->method(0), controller,
                       request, response, done);
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_steammessages_5fhelprequest_2esteamworkssdk_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
