// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: steammessages_oauth.steamworkssdk.proto
// Protobuf C++ Version: 7.35.1

#include "steammessages_oauth.steamworkssdk.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
#ifdef PROTOBUF_MESSAGE_GLOBALS
namespace {
PROTOBUF_CONSTINIT ::google::protobuf::internal::ReflectionData
    file_reflection_data[] = {
        // ::COAuthToken_ImplicitGrantNoPrompt_Request
        {&::_pbi::kDescriptorMethods, &::descriptor_table_steammessages_5foauth_2esteamworkssdk_2eproto, /* tracker*/ nullptr,},
        // ::COAuthToken_ImplicitGrantNoPrompt_Response
        {&::_pbi::kDescriptorMethods, &::descriptor_table_steammessages_5foauth_2esteamworkssdk_2eproto, /* tracker*/ nullptr,},
};
}  // namespace
#endif
class COAuthToken_ImplicitGrantNoPrompt_Response::_Internal {
 public:
  using HasBits = decltype(::std::declval<COAuthToken_ImplicitGrantNoPrompt_Response>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(COAuthToken_ImplicitGrantNoPrompt_Response, _impl_._has_bits_);
};

constexpr COAuthToken_ImplicitGrantNoPrompt_Response::ParseTableT_ COAuthToken_ImplicitGrantNoPrompt_Response::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(COAuthToken_ImplicitGrantNoPrompt_Response, _impl_._has_bits_),
      0, // no _extensions_
      2, 8,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967292,  // skipmap
      offsetof(ParseTableT_, field_entries),
      2,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::COAuthToken_ImplicitGrantNoPrompt_Response>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      // optional string redirect_uri = 2 [(.description) = "Redirection URI provided during client registration."];
      {::_pbi::TcParser::FastBS1,
       {18, 1, 0,
        PROTOBUF_FIELD_OFFSET(COAuthToken_ImplicitGrantNoPrompt_Response, _impl_.redirect_uri_)}},
      // optional string access_token = 1 [(.description) = "OAuth Token, granted on success"];
      {::_pbi::TcParser::FastBS1,
       {10, 0, 0,
        PROTOBUF_FIELD_OFFSET(COAuthToken_ImplicitGrantNoPrompt_Response, _impl_.access_token_)}},
    }}, {{
      65535, 65535
    }}, {{
      // optional string access_token = 1 [(.description) = "OAuth Token, granted on success"];
      {PROTOBUF_FIELD_OFFSET(COAuthToken_ImplicitGrantNoPrompt_Response, _impl_.access_token_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
      // optional string redirect_uri = 2 [(.description) = "Redirection URI provided during client registration."];
      {PROTOBUF_FIELD_OFFSET(COAuthToken_ImplicitGrantNoPrompt_Response, _impl_.redirect_uri_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    }},
    // no aux_entries
    {{
    }},
  };
}


inline constexpr COAuthToken_ImplicitGrantNoPrompt_Response::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        access_token_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        redirect_uri_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
constexpr COAuthToken_ImplicitGrantNoPrompt_Response::COAuthToken_ImplicitGrantNoPrompt_Response(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::Message(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL COAuthToken_ImplicitGrantNoPrompt_Response::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) COAuthToken_ImplicitGrantNoPrompt_Response(arena);
}
constexpr auto COAuthToken_ImplicitGrantNoPrompt_Response::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(COAuthToken_ImplicitGrantNoPrompt_Response), alignof(COAuthToken_ImplicitGrantNoPrompt_Response));
}
constexpr auto COAuthToken_ImplicitGrantNoPrompt_Response::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &COAuthToken_ImplicitGrantNoPrompt_Response::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<COAuthToken_ImplicitGrantNoPrompt_Response>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &COAuthToken_ImplicitGrantNoPrompt_Response::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<COAuthToken_ImplicitGrantNoPrompt_Response>(), &COAuthToken_ImplicitGrantNoPrompt_Response::ByteSizeLong,
              &COAuthToken_ImplicitGrantNoPrompt_Response::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(COAuthToken_ImplicitGrantNoPrompt_Response, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[1],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_steammessages_5foauth_2esteamworkssdk_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct COAuthToken_ImplicitGrantNoPrompt_ResponseGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr COAuthToken_ImplicitGrantNoPrompt_ResponseGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 COAuthToken_ImplicitGrantNoPrompt_Response_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(COAuthToken_ImplicitGrantNoPrompt_Response::InternalGenerateClassData_(
            _default, &COAuthToken_ImplicitGrantNoPrompt_Response_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<COAuthToken_ImplicitGrantNoPrompt_Response>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~COAuthToken_ImplicitGrantNoPrompt_ResponseGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) COAuthToken_ImplicitGrantNoPrompt_Response _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<COAuthToken_ImplicitGrantNoPrompt_Response>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(COAuthToken_ImplicitGrantNoPrompt_ResponseGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST COAuthToken_ImplicitGrantNoPrompt_ResponseGlobalsTypeInternal COAuthToken_ImplicitGrantNoPrompt_Response_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* COAuthToken_ImplicitGrantNoPrompt_Response_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return COAuthToken_ImplicitGrantNoPrompt_Response_globals_.GetClassData();
#else
  return COAuthToken_ImplicitGrantNoPrompt_Response_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
class COAuthToken_ImplicitGrantNoPrompt_Request::_Internal {
 public:
  using HasBits = decltype(::std::declval<COAuthToken_ImplicitGrantNoPrompt_Request>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(COAuthToken_ImplicitGrantNoPrompt_Request, _impl_._has_bits_);
};

constexpr COAuthToken_ImplicitGrantNoPrompt_Request::ParseTableT_ COAuthToken_ImplicitGrantNoPrompt_Request::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(COAuthToken_ImplicitGrantNoPrompt_Request, _impl_._has_bits_),
      0, // no _extensions_
      1, 0,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967294,  // skipmap
      offsetof(ParseTableT_, field_entries),
      1,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::COAuthToken_ImplicitGrantNoPrompt_Request>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      // optional string clientid = 1 [(.description) = "Client ID for which to count the number of issued tokens"];
      {::_pbi::TcParser::FastBS1,
       {10, 0, 0,
        PROTOBUF_FIELD_OFFSET(COAuthToken_ImplicitGrantNoPrompt_Request, _impl_.clientid_)}},
    }}, {{
      65535, 65535
    }}, {{
      // optional string clientid = 1 [(.description) = "Client ID for which to count the number of issued tokens"];
      {PROTOBUF_FIELD_OFFSET(COAuthToken_ImplicitGrantNoPrompt_Request, _impl_.clientid_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    }},
    // no aux_entries
    {{
    }},
  };
}


inline constexpr COAuthToken_ImplicitGrantNoPrompt_Request::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        clientid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
constexpr COAuthToken_ImplicitGrantNoPrompt_Request::COAuthToken_ImplicitGrantNoPrompt_Request(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::Message(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL COAuthToken_ImplicitGrantNoPrompt_Request::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) COAuthToken_ImplicitGrantNoPrompt_Request(arena);
}
constexpr auto COAuthToken_ImplicitGrantNoPrompt_Request::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(COAuthToken_ImplicitGrantNoPrompt_Request), alignof(COAuthToken_ImplicitGrantNoPrompt_Request));
}
constexpr auto COAuthToken_ImplicitGrantNoPrompt_Request::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &COAuthToken_ImplicitGrantNoPrompt_Request::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<COAuthToken_ImplicitGrantNoPrompt_Request>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &COAuthToken_ImplicitGrantNoPrompt_Request::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<COAuthToken_ImplicitGrantNoPrompt_Request>(), &COAuthToken_ImplicitGrantNoPrompt_Request::ByteSizeLong,
              &COAuthToken_ImplicitGrantNoPrompt_Request::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(COAuthToken_ImplicitGrantNoPrompt_Request, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[0],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_steammessages_5foauth_2esteamworkssdk_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct COAuthToken_ImplicitGrantNoPrompt_RequestGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr COAuthToken_ImplicitGrantNoPrompt_RequestGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 COAuthToken_ImplicitGrantNoPrompt_Request_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(COAuthToken_ImplicitGrantNoPrompt_Request::InternalGenerateClassData_(
            _default, &COAuthToken_ImplicitGrantNoPrompt_Request_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<COAuthToken_ImplicitGrantNoPrompt_Request>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~COAuthToken_ImplicitGrantNoPrompt_RequestGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) COAuthToken_ImplicitGrantNoPrompt_Request _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<COAuthToken_ImplicitGrantNoPrompt_Request>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(COAuthToken_ImplicitGrantNoPrompt_RequestGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST COAuthToken_ImplicitGrantNoPrompt_RequestGlobalsTypeInternal COAuthToken_ImplicitGrantNoPrompt_Request_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* COAuthToken_ImplicitGrantNoPrompt_Request_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return COAuthToken_ImplicitGrantNoPrompt_Request_globals_.GetClassData();
#else
  return COAuthToken_ImplicitGrantNoPrompt_Request_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_steammessages_5foauth_2esteamworkssdk_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_steammessages_5foauth_2esteamworkssdk_2eproto = nullptr;
const ::uint32_t
    TableStruct_steammessages_5foauth_2esteamworkssdk_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::COAuthToken_ImplicitGrantNoPrompt_Request, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::COAuthToken_ImplicitGrantNoPrompt_Request, _impl_.clientid_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::COAuthToken_ImplicitGrantNoPrompt_Response, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::COAuthToken_ImplicitGrantNoPrompt_Response, _impl_.access_token_),
        PROTOBUF_FIELD_OFFSET(::COAuthToken_ImplicitGrantNoPrompt_Response, _impl_.redirect_uri_),
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::COAuthToken_ImplicitGrantNoPrompt_Request)},
        {5, sizeof(::COAuthToken_ImplicitGrantNoPrompt_Response)},
};
static const ::_pbi::MessageGlobalsBase* PROTOBUF_NONNULL const
    file_message_globals[] = {
        &::COAuthToken_ImplicitGrantNoPrompt_Request_globals_,
        &::COAuthToken_ImplicitGrantNoPrompt_Response_globals_,
};
const char descriptor_table_protodef_steammessages_5foauth_2esteamworkssdk_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\'steammessages_oauth.steamworkssdk.prot"
    "o\032.steammessages_unified_base.steamworks"
    "sdk.proto\"{\n)COAuthToken_ImplicitGrantNo"
    "Prompt_Request\022N\n\010clientid\030\001 \001(\tB<\202\265\0308Cl"
    "ient ID for which to count the number of"
    " issued tokens\"\267\001\n*COAuthToken_ImplicitG"
    "rantNoPrompt_Response\0229\n\014access_token\030\001 "
    "\001(\tB#\202\265\030\037OAuth Token, granted on success"
    "\022N\n\014redirect_uri\030\002 \001(\tB8\202\265\0304Redirection "
    "URI provided during client registration."
    "2\261\002\n\nOAuthToken\022\353\001\n\025ImplicitGrantNoPromp"
    "t\022*.COAuthToken_ImplicitGrantNoPrompt_Re"
    "quest\032+.COAuthToken_ImplicitGrantNoPromp"
    "t_Response\"y\202\265\030uGrants an implicit OAuth"
    " token (grant type \'token\') for the spec"
    "ified client ID on behalf of a user with"
    "out prompting\0325\202\265\0301Service containing me"
    "thods to manage OAuth tokens"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_steammessages_5foauth_2esteamworkssdk_2eproto_deps[1] = {
        &::descriptor_table_steammessages_5funified_5fbase_2esteamworkssdk_2eproto,
};
static ::absl::once_flag descriptor_table_steammessages_5foauth_2esteamworkssdk_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_steammessages_5foauth_2esteamworkssdk_2eproto = {
    false,
    false,
    708,
    descriptor_table_protodef_steammessages_5foauth_2esteamworkssdk_2eproto,
    "steammessages_oauth.steamworkssdk.proto",
    &descriptor_table_steammessages_5foauth_2esteamworkssdk_2eproto_once,
    descriptor_table_steammessages_5foauth_2esteamworkssdk_2eproto_deps,
    1,
    2,
    schemas,
    file_message_globals,
    TableStruct_steammessages_5foauth_2esteamworkssdk_2eproto::offsets,
    file_level_enum_descriptors_steammessages_5foauth_2esteamworkssdk_2eproto,
    file_level_service_descriptors_steammessages_5foauth_2esteamworkssdk_2eproto,
};
// ===================================================================

COAuthToken_ImplicitGrantNoPrompt_Request::COAuthToken_ImplicitGrantNoPrompt_Request(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, COAuthToken_ImplicitGrantNoPrompt_Request_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:COAuthToken_ImplicitGrantNoPrompt_Request)
}
PROTOBUF_NDEBUG_INLINE COAuthToken_ImplicitGrantNoPrompt_Request::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::COAuthToken_ImplicitGrantNoPrompt_Request& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        clientid_(arena, from.clientid_) {}

COAuthToken_ImplicitGrantNoPrompt_Request::COAuthToken_ImplicitGrantNoPrompt_Request(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const COAuthToken_ImplicitGrantNoPrompt_Request& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, COAuthToken_ImplicitGrantNoPrompt_Request_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  COAuthToken_ImplicitGrantNoPrompt_Request* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:COAuthToken_ImplicitGrantNoPrompt_Request)
}
PROTOBUF_NDEBUG_INLINE COAuthToken_ImplicitGrantNoPrompt_Request::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        clientid_(arena) {}

inline void COAuthToken_ImplicitGrantNoPrompt_Request::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
COAuthToken_ImplicitGrantNoPrompt_Request::~COAuthToken_ImplicitGrantNoPrompt_Request() {
  // @@protoc_insertion_point(destructor:COAuthToken_ImplicitGrantNoPrompt_Request)
  SharedDtor(*this);
}
inline void COAuthToken_ImplicitGrantNoPrompt_Request::SharedDtor(MessageLite& self) {
  COAuthToken_ImplicitGrantNoPrompt_Request& this_ = static_cast<COAuthToken_ImplicitGrantNoPrompt_Request&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.clientid_.Destroy();
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull COAuthToken_ImplicitGrantNoPrompt_Request_class_data_ =
        COAuthToken_ImplicitGrantNoPrompt_Request::InternalGenerateClassData_(COAuthToken_ImplicitGrantNoPrompt_Request_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
COAuthToken_ImplicitGrantNoPrompt_Request::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&COAuthToken_ImplicitGrantNoPrompt_Request_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(COAuthToken_ImplicitGrantNoPrompt_Request_class_data_.tc_table);
  return COAuthToken_ImplicitGrantNoPrompt_Request_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
COAuthToken_ImplicitGrantNoPrompt_Request::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&COAuthToken_ImplicitGrantNoPrompt_Request_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&COAuthToken_ImplicitGrantNoPrompt_Request_globals_));
  return COAuthToken_ImplicitGrantNoPrompt_Request_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const COAuthToken_ImplicitGrantNoPrompt_Request::ParseTableT_
    COAuthToken_ImplicitGrantNoPrompt_Request::_table_ =
        COAuthToken_ImplicitGrantNoPrompt_Request::InternalGenerateParseTable_(COAuthToken_ImplicitGrantNoPrompt_Request_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void COAuthToken_ImplicitGrantNoPrompt_Request::Clear() {
// @@protoc_insertion_point(message_clear_start:COAuthToken_ImplicitGrantNoPrompt_Request)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.clientid_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL COAuthToken_ImplicitGrantNoPrompt_Request::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const COAuthToken_ImplicitGrantNoPrompt_Request& this_ = static_cast<const COAuthToken_ImplicitGrantNoPrompt_Request&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL COAuthToken_ImplicitGrantNoPrompt_Request::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const COAuthToken_ImplicitGrantNoPrompt_Request& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:COAuthToken_ImplicitGrantNoPrompt_Request)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional string clientid = 1 [(.description) = "Client ID for which to count the number of issued tokens"];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    const ::std::string& _s = this_._internal_clientid();
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:COAuthToken_ImplicitGrantNoPrompt_Request)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t COAuthToken_ImplicitGrantNoPrompt_Request::ByteSizeLong(const MessageLite& base) {
  const COAuthToken_ImplicitGrantNoPrompt_Request& this_ = static_cast<const COAuthToken_ImplicitGrantNoPrompt_Request&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t COAuthToken_ImplicitGrantNoPrompt_Request::ByteSizeLong() const {
  const COAuthToken_ImplicitGrantNoPrompt_Request& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:COAuthToken_ImplicitGrantNoPrompt_Request)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // optional string clientid = 1 [(.description) = "Client ID for which to count the number of issued tokens"];
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_clientid());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void COAuthToken_ImplicitGrantNoPrompt_Request::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<COAuthToken_ImplicitGrantNoPrompt_Request*>(&to_msg);
  auto& from = static_cast<const COAuthToken_ImplicitGrantNoPrompt_Request&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:COAuthToken_ImplicitGrantNoPrompt_Request)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _this->_internal_set_clientid(from._internal_clientid());
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void COAuthToken_ImplicitGrantNoPrompt_Request::CopyFrom(const COAuthToken_ImplicitGrantNoPrompt_Request& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:COAuthToken_ImplicitGrantNoPrompt_Request)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void COAuthToken_ImplicitGrantNoPrompt_Request::InternalSwap(COAuthToken_ImplicitGrantNoPrompt_Request* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.clientid_, &other->_impl_.clientid_, arena);
}

::google::protobuf::Metadata COAuthToken_ImplicitGrantNoPrompt_Request::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

COAuthToken_ImplicitGrantNoPrompt_Response::COAuthToken_ImplicitGrantNoPrompt_Response(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, COAuthToken_ImplicitGrantNoPrompt_Response_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:COAuthToken_ImplicitGrantNoPrompt_Response)
}
PROTOBUF_NDEBUG_INLINE COAuthToken_ImplicitGrantNoPrompt_Response::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::COAuthToken_ImplicitGrantNoPrompt_Response& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        access_token_(arena, from.access_token_),
        redirect_uri_(arena, from.redirect_uri_) {}

COAuthToken_ImplicitGrantNoPrompt_Response::COAuthToken_ImplicitGrantNoPrompt_Response(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const COAuthToken_ImplicitGrantNoPrompt_Response& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, COAuthToken_ImplicitGrantNoPrompt_Response_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  COAuthToken_ImplicitGrantNoPrompt_Response* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:COAuthToken_ImplicitGrantNoPrompt_Response)
}
PROTOBUF_NDEBUG_INLINE COAuthToken_ImplicitGrantNoPrompt_Response::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        access_token_(arena),
        redirect_uri_(arena) {}

inline void COAuthToken_ImplicitGrantNoPrompt_Response::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
COAuthToken_ImplicitGrantNoPrompt_Response::~COAuthToken_ImplicitGrantNoPrompt_Response() {
  // @@protoc_insertion_point(destructor:COAuthToken_ImplicitGrantNoPrompt_Response)
  SharedDtor(*this);
}
inline void COAuthToken_ImplicitGrantNoPrompt_Response::SharedDtor(MessageLite& self) {
  COAuthToken_ImplicitGrantNoPrompt_Response& this_ = static_cast<COAuthToken_ImplicitGrantNoPrompt_Response&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.access_token_.Destroy();
  this_._impl_.redirect_uri_.Destroy();
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull COAuthToken_ImplicitGrantNoPrompt_Response_class_data_ =
        COAuthToken_ImplicitGrantNoPrompt_Response::InternalGenerateClassData_(COAuthToken_ImplicitGrantNoPrompt_Response_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
COAuthToken_ImplicitGrantNoPrompt_Response::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&COAuthToken_ImplicitGrantNoPrompt_Response_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(COAuthToken_ImplicitGrantNoPrompt_Response_class_data_.tc_table);
  return COAuthToken_ImplicitGrantNoPrompt_Response_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
COAuthToken_ImplicitGrantNoPrompt_Response::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&COAuthToken_ImplicitGrantNoPrompt_Response_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&COAuthToken_ImplicitGrantNoPrompt_Response_globals_));
  return COAuthToken_ImplicitGrantNoPrompt_Response_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const COAuthToken_ImplicitGrantNoPrompt_Response::ParseTableT_
    COAuthToken_ImplicitGrantNoPrompt_Response::_table_ =
        COAuthToken_ImplicitGrantNoPrompt_Response::InternalGenerateParseTable_(COAuthToken_ImplicitGrantNoPrompt_Response_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void COAuthToken_ImplicitGrantNoPrompt_Response::Clear() {
// @@protoc_insertion_point(message_clear_start:COAuthToken_ImplicitGrantNoPrompt_Response)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.access_token_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.redirect_uri_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL COAuthToken_ImplicitGrantNoPrompt_Response::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const COAuthToken_ImplicitGrantNoPrompt_Response& this_ = static_cast<const COAuthToken_ImplicitGrantNoPrompt_Response&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL COAuthToken_ImplicitGrantNoPrompt_Response::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const COAuthToken_ImplicitGrantNoPrompt_Response& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:COAuthToken_ImplicitGrantNoPrompt_Response)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional string access_token = 1 [(.description) = "OAuth Token, granted on success"];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    const ::std::string& _s = this_._internal_access_token();
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // optional string redirect_uri = 2 [(.description) = "Redirection URI provided during client registration."];
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    const ::std::string& _s = this_._internal_redirect_uri();
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:COAuthToken_ImplicitGrantNoPrompt_Response)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t COAuthToken_ImplicitGrantNoPrompt_Response::ByteSizeLong(const MessageLite& base) {
  const COAuthToken_ImplicitGrantNoPrompt_Response& this_ = static_cast<const COAuthToken_ImplicitGrantNoPrompt_Response&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t COAuthToken_ImplicitGrantNoPrompt_Response::ByteSizeLong() const {
  const COAuthToken_ImplicitGrantNoPrompt_Response& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:COAuthToken_ImplicitGrantNoPrompt_Response)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // optional string access_token = 1 [(.description) = "OAuth Token, granted on success"];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_access_token());
    }
    // optional string redirect_uri = 2 [(.description) = "Redirection URI provided during client registration."];
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_redirect_uri());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void COAuthToken_ImplicitGrantNoPrompt_Response::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<COAuthToken_ImplicitGrantNoPrompt_Response*>(&to_msg);
  auto& from = static_cast<const COAuthToken_ImplicitGrantNoPrompt_Response&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:COAuthToken_ImplicitGrantNoPrompt_Response)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_set_access_token(from._internal_access_token());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_internal_set_redirect_uri(from._internal_redirect_uri());
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void COAuthToken_ImplicitGrantNoPrompt_Response::CopyFrom(const COAuthToken_ImplicitGrantNoPrompt_Response& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:COAuthToken_ImplicitGrantNoPrompt_Response)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void COAuthToken_ImplicitGrantNoPrompt_Response::InternalSwap(COAuthToken_ImplicitGrantNoPrompt_Response* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.access_token_, &other->_impl_.access_token_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.redirect_uri_, &other->_impl_.redirect_uri_, arena);
}

::google::protobuf::Metadata COAuthToken_ImplicitGrantNoPrompt_Response::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_steammessages_5foauth_2esteamworkssdk_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
