// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: uifontfile_format.proto
// Protobuf C++ Version: 7.35.1

#ifndef uifontfile_5fformat_2eproto_2epb_2eh
#define uifontfile_5fformat_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7035001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_uifontfile_5fformat_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_uifontfile_5fformat_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_uifontfile_5fformat_2eproto;
}  // extern "C"
class CUIFontFilePB;
struct CUIFontFilePBGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern CUIFontFilePBGlobalsTypeInternal CUIFontFilePB_globals_;
extern const ::google::protobuf::internal::ClassDataFull CUIFontFilePB_class_data_;
#else
extern const CUIFontFilePBGlobalsTypeInternal CUIFontFilePB_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
class CUIFontFilePackagePB;
struct CUIFontFilePackagePBGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern CUIFontFilePackagePBGlobalsTypeInternal CUIFontFilePackagePB_globals_;
extern const ::google::protobuf::internal::ClassDataFull CUIFontFilePackagePB_class_data_;
#else
extern const CUIFontFilePackagePBGlobalsTypeInternal CUIFontFilePackagePB_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
class CUIFontFilePackagePB_CUIEncryptedFontFilePB;
struct CUIFontFilePackagePB_CUIEncryptedFontFilePBGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern CUIFontFilePackagePB_CUIEncryptedFontFilePBGlobalsTypeInternal CUIFontFilePackagePB_CUIEncryptedFontFilePB_globals_;
extern const ::google::protobuf::internal::ClassDataFull CUIFontFilePackagePB_CUIEncryptedFontFilePB_class_data_;
#else
extern const CUIFontFilePackagePB_CUIEncryptedFontFilePBGlobalsTypeInternal CUIFontFilePackagePB_CUIEncryptedFontFilePB_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED CUIFontFilePackagePB_CUIEncryptedFontFilePB final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:CUIFontFilePackagePB.CUIEncryptedFontFilePB) */ {
 public:
  inline CUIFontFilePackagePB_CUIEncryptedFontFilePB() : CUIFontFilePackagePB_CUIEncryptedFontFilePB(nullptr) {}
  ~CUIFontFilePackagePB_CUIEncryptedFontFilePB() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CUIFontFilePackagePB_CUIEncryptedFontFilePB* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CUIFontFilePackagePB_CUIEncryptedFontFilePB));
  }
#endif

  template <typename = void>
  explicit constexpr CUIFontFilePackagePB_CUIEncryptedFontFilePB(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline CUIFontFilePackagePB_CUIEncryptedFontFilePB(const CUIFontFilePackagePB_CUIEncryptedFontFilePB& from) : CUIFontFilePackagePB_CUIEncryptedFontFilePB(nullptr, from) {}
  inline CUIFontFilePackagePB_CUIEncryptedFontFilePB(CUIFontFilePackagePB_CUIEncryptedFontFilePB&& from) noexcept : CUIFontFilePackagePB_CUIEncryptedFontFilePB(nullptr, ::std::move(from)) {}
  inline CUIFontFilePackagePB_CUIEncryptedFontFilePB& operator=(const CUIFontFilePackagePB_CUIEncryptedFontFilePB& from) {
    CopyFrom(from);
    return *this;
  }
  inline CUIFontFilePackagePB_CUIEncryptedFontFilePB& operator=(CUIFontFilePackagePB_CUIEncryptedFontFilePB&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const CUIFontFilePackagePB_CUIEncryptedFontFilePB& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<CUIFontFilePackagePB_CUIEncryptedFontFilePB>(&CUIFontFilePackagePB_CUIEncryptedFontFilePB_globals_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(CUIFontFilePackagePB_CUIEncryptedFontFilePB& a, CUIFontFilePackagePB_CUIEncryptedFontFilePB& b) { a.Swap(&b); }
  inline void Swap(CUIFontFilePackagePB_CUIEncryptedFontFilePB* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CUIFontFilePackagePB_CUIEncryptedFontFilePB* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] CUIFontFilePackagePB_CUIEncryptedFontFilePB* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CUIFontFilePackagePB_CUIEncryptedFontFilePB>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CUIFontFilePackagePB_CUIEncryptedFontFilePB& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CUIFontFilePackagePB_CUIEncryptedFontFilePB& from) { CUIFontFilePackagePB_CUIEncryptedFontFilePB::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CUIFontFilePackagePB_CUIEncryptedFontFilePB* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "CUIFontFilePackagePB.CUIEncryptedFontFilePB"; }

  explicit CUIFontFilePackagePB_CUIEncryptedFontFilePB(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CUIFontFilePackagePB_CUIEncryptedFontFilePB(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CUIFontFilePackagePB_CUIEncryptedFontFilePB& from);
  CUIFontFilePackagePB_CUIEncryptedFontFilePB(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CUIFontFilePackagePB_CUIEncryptedFontFilePB&& from) noexcept
      : CUIFontFilePackagePB_CUIEncryptedFontFilePB(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kEncryptedContentsFieldNumber = 1,
  };
  // optional bytes encrypted_contents = 1;
  [[nodiscard]] bool has_encrypted_contents()
      const;
  void clear_encrypted_contents() ;
  [[nodiscard]] const ::std::string& encrypted_contents() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_encrypted_contents(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_encrypted_contents();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_encrypted_contents();
  void set_allocated_encrypted_contents(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_encrypted_contents() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_encrypted_contents(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_encrypted_contents();

  public:
  // @@protoc_insertion_point(class_scope:CUIFontFilePackagePB.CUIEncryptedFontFilePB)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<0, 1,
                          0, 0,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CUIFontFilePackagePB_CUIEncryptedFontFilePB& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr encrypted_contents_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_uifontfile_5fformat_2eproto;
};
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED CUIFontFilePB final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:CUIFontFilePB) */ {
 public:
  inline CUIFontFilePB() : CUIFontFilePB(nullptr) {}
  ~CUIFontFilePB() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CUIFontFilePB* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CUIFontFilePB));
  }
#endif

  template <typename = void>
  explicit constexpr CUIFontFilePB(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline CUIFontFilePB(const CUIFontFilePB& from) : CUIFontFilePB(nullptr, from) {}
  inline CUIFontFilePB(CUIFontFilePB&& from) noexcept : CUIFontFilePB(nullptr, ::std::move(from)) {}
  inline CUIFontFilePB& operator=(const CUIFontFilePB& from) {
    CopyFrom(from);
    return *this;
  }
  inline CUIFontFilePB& operator=(CUIFontFilePB&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const CUIFontFilePB& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<CUIFontFilePB>(&CUIFontFilePB_globals_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(CUIFontFilePB& a, CUIFontFilePB& b) { a.Swap(&b); }
  inline void Swap(CUIFontFilePB* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CUIFontFilePB* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] CUIFontFilePB* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CUIFontFilePB>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CUIFontFilePB& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CUIFontFilePB& from) { CUIFontFilePB::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CUIFontFilePB* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "CUIFontFilePB"; }

  explicit CUIFontFilePB(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CUIFontFilePB(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CUIFontFilePB& from);
  CUIFontFilePB(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CUIFontFilePB&& from) noexcept
      : CUIFontFilePB(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kFontFileNameFieldNumber = 1,
    kOpentypeFontDataFieldNumber = 2,
  };
  // optional string font_file_name = 1;
  [[nodiscard]] bool has_font_file_name()
      const;
  void clear_font_file_name() ;
  [[nodiscard]] const ::std::string& font_file_name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_font_file_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_font_file_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_font_file_name();
  void set_allocated_font_file_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_font_file_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_font_file_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_font_file_name();

  public:
  // optional bytes opentype_font_data = 2;
  [[nodiscard]] bool has_opentype_font_data()
      const;
  void clear_opentype_font_data() ;
  [[nodiscard]] const ::std::string& opentype_font_data() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_opentype_font_data(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_opentype_font_data();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_opentype_font_data();
  void set_allocated_opentype_font_data(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_opentype_font_data() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_opentype_font_data(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_opentype_font_data();

  public:
  // @@protoc_insertion_point(class_scope:CUIFontFilePB)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<1, 2,
                          0, 0,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CUIFontFilePB& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr font_file_name_;
    ::google::protobuf::internal::ArenaStringPtr opentype_font_data_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_uifontfile_5fformat_2eproto;
};
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED CUIFontFilePackagePB final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:CUIFontFilePackagePB) */ {
 public:
  inline CUIFontFilePackagePB() : CUIFontFilePackagePB(nullptr) {}
  ~CUIFontFilePackagePB() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CUIFontFilePackagePB* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CUIFontFilePackagePB));
  }
#endif

  template <typename = void>
  explicit constexpr CUIFontFilePackagePB(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline CUIFontFilePackagePB(const CUIFontFilePackagePB& from) : CUIFontFilePackagePB(nullptr, from) {}
  inline CUIFontFilePackagePB(CUIFontFilePackagePB&& from) noexcept : CUIFontFilePackagePB(nullptr, ::std::move(from)) {}
  inline CUIFontFilePackagePB& operator=(const CUIFontFilePackagePB& from) {
    CopyFrom(from);
    return *this;
  }
  inline CUIFontFilePackagePB& operator=(CUIFontFilePackagePB&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const CUIFontFilePackagePB& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<CUIFontFilePackagePB>(&CUIFontFilePackagePB_globals_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(CUIFontFilePackagePB& a, CUIFontFilePackagePB& b) { a.Swap(&b); }
  inline void Swap(CUIFontFilePackagePB* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CUIFontFilePackagePB* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] CUIFontFilePackagePB* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CUIFontFilePackagePB>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CUIFontFilePackagePB& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CUIFontFilePackagePB& from) { CUIFontFilePackagePB::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CUIFontFilePackagePB* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "CUIFontFilePackagePB"; }

  explicit CUIFontFilePackagePB(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CUIFontFilePackagePB(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CUIFontFilePackagePB& from);
  CUIFontFilePackagePB(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CUIFontFilePackagePB&& from) noexcept
      : CUIFontFilePackagePB(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using CUIEncryptedFontFilePB = CUIFontFilePackagePB_CUIEncryptedFontFilePB;

  // accessors -------------------------------------------------------
  enum : int {
    kEncryptedFontFilesFieldNumber = 2,
    kPackageVersionFieldNumber = 1,
  };
  // repeated .CUIFontFilePackagePB.CUIEncryptedFontFilePB encrypted_font_files = 2;
  [[nodiscard]] int encrypted_font_files_size()
      const;
  private:
  int _internal_encrypted_font_files_size() const;

  public:
  void clear_encrypted_font_files() ;
  [[nodiscard]] const ::CUIFontFilePackagePB_CUIEncryptedFontFilePB& encrypted_font_files(int index) const;
  [[nodiscard]] ::CUIFontFilePackagePB_CUIEncryptedFontFilePB* PROTOBUF_NONNULL mutable_encrypted_font_files(int index);
  ::CUIFontFilePackagePB_CUIEncryptedFontFilePB* PROTOBUF_NONNULL add_encrypted_font_files();
  [[nodiscard]] const ::google::protobuf::RepeatedPtrField<::CUIFontFilePackagePB_CUIEncryptedFontFilePB>&
  encrypted_font_files() const;
  [[nodiscard]] ::google::protobuf::RepeatedPtrField<::CUIFontFilePackagePB_CUIEncryptedFontFilePB>* PROTOBUF_NONNULL
  mutable_encrypted_font_files();

  private:
  const ::google::protobuf::RepeatedPtrField<::CUIFontFilePackagePB_CUIEncryptedFontFilePB>& _internal_encrypted_font_files() const;
  ::google::protobuf::RepeatedPtrField<::CUIFontFilePackagePB_CUIEncryptedFontFilePB>* PROTOBUF_NONNULL _internal_mutable_encrypted_font_files();

  public:
  // optional uint32 package_version = 1;
  [[nodiscard]] bool has_package_version()
      const;
  void clear_package_version() ;
  [[nodiscard]] ::uint32_t package_version() const;
  void set_package_version(::uint32_t value);

  private:
  ::uint32_t _internal_package_version() const;
  void _internal_set_package_version(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:CUIFontFilePackagePB)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<1, 2,
                          1, 0,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CUIFontFilePackagePB& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::CUIFontFilePackagePB_CUIEncryptedFontFilePB > encrypted_font_files_;
    ::uint32_t package_version_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_uifontfile_5fformat_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// CUIFontFilePB

// optional string font_file_name = 1;
inline bool CUIFontFilePB::has_font_file_name() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void CUIFontFilePB::clear_font_file_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.font_file_name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline const ::std::string& CUIFontFilePB::font_file_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:CUIFontFilePB.font_file_name)
  return _internal_font_file_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CUIFontFilePB::set_font_file_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.font_file_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:CUIFontFilePB.font_file_name)
}
inline ::std::string* PROTOBUF_NONNULL CUIFontFilePB::mutable_font_file_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_font_file_name();
  // @@protoc_insertion_point(field_mutable:CUIFontFilePB.font_file_name)
  return _s;
}
inline const ::std::string& CUIFontFilePB::_internal_font_file_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.font_file_name_.Get();
}
inline void CUIFontFilePB::_internal_set_font_file_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.font_file_name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CUIFontFilePB::_internal_mutable_font_file_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.font_file_name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CUIFontFilePB::release_font_file_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:CUIFontFilePB.font_file_name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.font_file_name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.font_file_name_.Set("", GetArena());
  }
  return released;
}
inline void CUIFontFilePB::set_allocated_font_file_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.font_file_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.font_file_name_.IsDefault()) {
    _impl_.font_file_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:CUIFontFilePB.font_file_name)
}

// optional bytes opentype_font_data = 2;
inline bool CUIFontFilePB::has_opentype_font_data() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void CUIFontFilePB::clear_opentype_font_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.opentype_font_data_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline const ::std::string& CUIFontFilePB::opentype_font_data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:CUIFontFilePB.opentype_font_data)
  return _internal_opentype_font_data();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CUIFontFilePB::set_opentype_font_data(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.opentype_font_data_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:CUIFontFilePB.opentype_font_data)
}
inline ::std::string* PROTOBUF_NONNULL CUIFontFilePB::mutable_opentype_font_data()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_opentype_font_data();
  // @@protoc_insertion_point(field_mutable:CUIFontFilePB.opentype_font_data)
  return _s;
}
inline const ::std::string& CUIFontFilePB::_internal_opentype_font_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.opentype_font_data_.Get();
}
inline void CUIFontFilePB::_internal_set_opentype_font_data(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.opentype_font_data_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CUIFontFilePB::_internal_mutable_opentype_font_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.opentype_font_data_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CUIFontFilePB::release_opentype_font_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:CUIFontFilePB.opentype_font_data)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.opentype_font_data_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.opentype_font_data_.Set("", GetArena());
  }
  return released;
}
inline void CUIFontFilePB::set_allocated_opentype_font_data(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.opentype_font_data_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.opentype_font_data_.IsDefault()) {
    _impl_.opentype_font_data_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:CUIFontFilePB.opentype_font_data)
}

// -------------------------------------------------------------------

// CUIFontFilePackagePB_CUIEncryptedFontFilePB

// optional bytes encrypted_contents = 1;
inline bool CUIFontFilePackagePB_CUIEncryptedFontFilePB::has_encrypted_contents() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void CUIFontFilePackagePB_CUIEncryptedFontFilePB::clear_encrypted_contents() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.encrypted_contents_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline const ::std::string& CUIFontFilePackagePB_CUIEncryptedFontFilePB::encrypted_contents() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:CUIFontFilePackagePB.CUIEncryptedFontFilePB.encrypted_contents)
  return _internal_encrypted_contents();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CUIFontFilePackagePB_CUIEncryptedFontFilePB::set_encrypted_contents(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.encrypted_contents_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:CUIFontFilePackagePB.CUIEncryptedFontFilePB.encrypted_contents)
}
inline ::std::string* PROTOBUF_NONNULL CUIFontFilePackagePB_CUIEncryptedFontFilePB::mutable_encrypted_contents()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_encrypted_contents();
  // @@protoc_insertion_point(field_mutable:CUIFontFilePackagePB.CUIEncryptedFontFilePB.encrypted_contents)
  return _s;
}
inline const ::std::string& CUIFontFilePackagePB_CUIEncryptedFontFilePB::_internal_encrypted_contents() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.encrypted_contents_.Get();
}
inline void CUIFontFilePackagePB_CUIEncryptedFontFilePB::_internal_set_encrypted_contents(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.encrypted_contents_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CUIFontFilePackagePB_CUIEncryptedFontFilePB::_internal_mutable_encrypted_contents() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.encrypted_contents_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CUIFontFilePackagePB_CUIEncryptedFontFilePB::release_encrypted_contents() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:CUIFontFilePackagePB.CUIEncryptedFontFilePB.encrypted_contents)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.encrypted_contents_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.encrypted_contents_.Set("", GetArena());
  }
  return released;
}
inline void CUIFontFilePackagePB_CUIEncryptedFontFilePB::set_allocated_encrypted_contents(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.encrypted_contents_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.encrypted_contents_.IsDefault()) {
    _impl_.encrypted_contents_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:CUIFontFilePackagePB.CUIEncryptedFontFilePB.encrypted_contents)
}

// -------------------------------------------------------------------

// CUIFontFilePackagePB

// optional uint32 package_version = 1;
inline bool CUIFontFilePackagePB::has_package_version() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void CUIFontFilePackagePB::clear_package_version() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.package_version_ = 0u;
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline ::uint32_t CUIFontFilePackagePB::package_version() const {
  // @@protoc_insertion_point(field_get:CUIFontFilePackagePB.package_version)
  return _internal_package_version();
}
inline void CUIFontFilePackagePB::set_package_version(::uint32_t value) {
  _internal_set_package_version(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:CUIFontFilePackagePB.package_version)
}
inline ::uint32_t CUIFontFilePackagePB::_internal_package_version() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.package_version_;
}
inline void CUIFontFilePackagePB::_internal_set_package_version(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.package_version_ = value;
}

// repeated .CUIFontFilePackagePB.CUIEncryptedFontFilePB encrypted_font_files = 2;
inline int CUIFontFilePackagePB::_internal_encrypted_font_files_size() const {
  return _internal_encrypted_font_files().size();
}
inline int CUIFontFilePackagePB::encrypted_font_files_size() const {
  return _internal_encrypted_font_files_size();
}
inline void CUIFontFilePackagePB::clear_encrypted_font_files() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.encrypted_font_files_.Clear();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline const ::CUIFontFilePackagePB_CUIEncryptedFontFilePB& CUIFontFilePackagePB::encrypted_font_files(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:CUIFontFilePackagePB.encrypted_font_files)
  return _internal_encrypted_font_files().Get(index);
}
inline ::CUIFontFilePackagePB_CUIEncryptedFontFilePB* PROTOBUF_NONNULL CUIFontFilePackagePB::mutable_encrypted_font_files(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:CUIFontFilePackagePB.encrypted_font_files)
  return _internal_mutable_encrypted_font_files()->Mutable(index);
}
inline ::CUIFontFilePackagePB_CUIEncryptedFontFilePB* PROTOBUF_NONNULL CUIFontFilePackagePB::add_encrypted_font_files()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::CUIFontFilePackagePB_CUIEncryptedFontFilePB* _add =
      _internal_mutable_encrypted_font_files()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:CUIFontFilePackagePB.encrypted_font_files)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::CUIFontFilePackagePB_CUIEncryptedFontFilePB>& CUIFontFilePackagePB::encrypted_font_files() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:CUIFontFilePackagePB.encrypted_font_files)
  return _internal_encrypted_font_files();
}
inline ::google::protobuf::RepeatedPtrField<::CUIFontFilePackagePB_CUIEncryptedFontFilePB>* PROTOBUF_NONNULL
CUIFontFilePackagePB::mutable_encrypted_font_files() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:CUIFontFilePackagePB.encrypted_font_files)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_encrypted_font_files();
}
inline const ::google::protobuf::RepeatedPtrField<::CUIFontFilePackagePB_CUIEncryptedFontFilePB>&
CUIFontFilePackagePB::_internal_encrypted_font_files() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.encrypted_font_files_;
}
inline ::google::protobuf::RepeatedPtrField<::CUIFontFilePackagePB_CUIEncryptedFontFilePB>* PROTOBUF_NONNULL
CUIFontFilePackagePB::_internal_mutable_encrypted_font_files() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.encrypted_font_files_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // uifontfile_5fformat_2eproto_2epb_2eh
