// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: valveextensions.proto
// Protobuf C++ Version: 7.36.0-rc2

#ifndef valveextensions_2eproto_2epb_2eh
#define valveextensions_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7036000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/descriptor.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_valveextensions_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_valveextensions_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_valveextensions_2eproto;
}  // extern "C"
enum EProtoDebugVisiblity : int;
extern const uint32_t EProtoDebugVisiblity_internal_data_[];
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::EProtoDebugVisiblity_internal_data_>
    internal::EnumTraitsImpl::value<::EProtoDebugVisiblity>;
}  // namespace protobuf
}  // namespace google

enum EProtoDebugVisiblity : int {
  k_EProtoDebugVisibility_Always = 0,
  k_EProtoDebugVisibility_Server = 70,
  k_EProtoDebugVisibility_ValveServer = 80,
  k_EProtoDebugVisibility_GC = 90,
  k_EProtoDebugVisibility_Never = 100,
};

extern const uint32_t EProtoDebugVisiblity_internal_data_[];
inline constexpr EProtoDebugVisiblity EProtoDebugVisiblity_MIN =
    static_cast<EProtoDebugVisiblity>(0);
inline constexpr EProtoDebugVisiblity EProtoDebugVisiblity_MAX =
    static_cast<EProtoDebugVisiblity>(100);
[[nodiscard]] inline bool EProtoDebugVisiblity_IsValid(int value) {
  return ::google::protobuf::internal::ValidateEnum(value, EProtoDebugVisiblity_internal_data_);
}
inline constexpr int EProtoDebugVisiblity_ARRAYSIZE = 100 + 1;
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
EProtoDebugVisiblity_descriptor();
[[nodiscard]] inline auto ProtobufInternalGetEnumDescriptor(EProtoDebugVisiblity) {
  return EProtoDebugVisiblity_descriptor();
}
template <typename T>
[[nodiscard]] const ::std::string& EProtoDebugVisiblity_Name(T value) {
  static_assert(::std::is_same<T, EProtoDebugVisiblity>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to EProtoDebugVisiblity_Name().");
  return ::google::protobuf::internal::NameOfEnum(EProtoDebugVisiblity_descriptor(), value);
}
[[nodiscard]] inline bool EProtoDebugVisiblity_Parse(
    ::absl::string_view name, EProtoDebugVisiblity* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<EProtoDebugVisiblity>(EProtoDebugVisiblity_descriptor(), name,
                                           value);
}
using ::google::protobuf::internal::generated_enum::AbslParseFlag;
using ::google::protobuf::internal::generated_enum::AbslUnparseFlag;

// ===================================================================



// ===================================================================



inline constexpr int kCodegenDeltaEncoderFieldNumber = 61000;
extern ::google::protobuf::internal::ExtensionIdentifier<
    ::google::protobuf::MessageOptions, ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false>(codegen_delta_encoder);
inline constexpr int kValveMapFieldFieldNumber = 61000;
extern ::google::protobuf::internal::ExtensionIdentifier<
    ::google::protobuf::FieldOptions, ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false>(valve_map_field);
inline constexpr int kValveMapKeyFieldNumber = 61001;
extern ::google::protobuf::internal::ExtensionIdentifier<
    ::google::protobuf::FieldOptions, ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false>(valve_map_key);
inline constexpr int kDiffEncodeFieldFieldNumber = 61002;
extern ::google::protobuf::internal::ExtensionIdentifier<
    ::google::protobuf::FieldOptions, ::google::protobuf::internal::PrimitiveTypeTraits< ::int32_t >, 5, false>(diff_encode_field);
inline constexpr int kDeltaIgnoreFieldNumber = 61003;
extern ::google::protobuf::internal::ExtensionIdentifier<
    ::google::protobuf::FieldOptions, ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false>(delta_ignore);
inline constexpr int kUntrustedDeltaMaxFieldNumber = 61008;
extern ::google::protobuf::internal::ExtensionIdentifier<
    ::google::protobuf::FieldOptions, ::google::protobuf::internal::PrimitiveTypeTraits< ::int32_t >, 5, false>(untrusted_delta_max);
inline constexpr int kSteammlMaxEntriesFieldNumber = 61004;
extern ::google::protobuf::internal::ExtensionIdentifier<
    ::google::protobuf::FieldOptions, ::google::protobuf::internal::PrimitiveTypeTraits< ::uint32_t >, 13, false>(steamml_max_entries);
inline constexpr int kSteammlIsTimestampFieldNumber = 61005;
extern ::google::protobuf::internal::ExtensionIdentifier<
    ::google::protobuf::FieldOptions, ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false>(steamml_is_timestamp);
inline constexpr int kSteamlearnCountFieldNumber = 61006;
extern ::google::protobuf::internal::ExtensionIdentifier<
    ::google::protobuf::FieldOptions, ::google::protobuf::internal::PrimitiveTypeTraits< ::uint32_t >, 13, false>(steamlearn_count);
inline constexpr int kDebugprintVisibilityFieldNumber = 61007;
extern ::google::protobuf::internal::ExtensionIdentifier<
    ::google::protobuf::FieldOptions, ::google::protobuf::internal::EnumTypeTraits< ::EProtoDebugVisiblity>, 14, false>(debugprint_visibility);
inline constexpr int kSchemaFriendlyNameFieldNumber = 1000;
extern ::google::protobuf::internal::ExtensionIdentifier<
    ::google::protobuf::EnumValueOptions, ::google::protobuf::internal::StringTypeTraits, 12, false>(schema_friendly_name);
inline constexpr int kSchemaDescriptionFieldNumber = 1001;
extern ::google::protobuf::internal::ExtensionIdentifier<
    ::google::protobuf::EnumValueOptions, ::google::protobuf::internal::StringTypeTraits, 12, false>(schema_description);
inline constexpr int kSchemaSuppressEnumeratorFieldNumber = 1002;
extern ::google::protobuf::internal::ExtensionIdentifier<
    ::google::protobuf::EnumValueOptions, ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false>(schema_suppress_enumerator);

// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::EProtoDebugVisiblity> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::EProtoDebugVisiblity>() {
  return ::EProtoDebugVisiblity_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // valveextensions_2eproto_2epb_2eh
