// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: valveextensions.proto
// Protobuf C++ Version: 7.36.0-rc2

#include "valveextensions.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_valveextensions_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_valveextensions_2eproto = nullptr;
const ::uint32_t TableStruct_valveextensions_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* PROTOBUF_NULLABLE schemas = nullptr;
static constexpr ::_pbi::MessageGlobalsBase* PROTOBUF_NONNULL const* PROTOBUF_NULLABLE
    file_message_globals = nullptr;
const char descriptor_table_protodef_valveextensions_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\025valveextensions.proto\032 google/protobuf"
    "/descriptor.proto*\312\001\n\024EProtoDebugVisibli"
    "ty\022\"\n\036k_EProtoDebugVisibility_Always\020\000\022\""
    "\n\036k_EProtoDebugVisibility_Server\020F\022\'\n#k_"
    "EProtoDebugVisibility_ValveServer\020P\022\036\n\032k"
    "_EProtoDebugVisibility_GC\020Z\022!\n\035k_EProtoD"
    "ebugVisibility_Never\020d:G\n\025codegen_delta_"
    "encoder\022\037.google.protobuf.MessageOptions"
    "\030\310\334\003 \001(\010:\005false:\?\n\017valve_map_field\022\035.goo"
    "gle.protobuf.FieldOptions\030\310\334\003 \001(\010:\005false"
    ":=\n\rvalve_map_key\022\035.google.protobuf.Fiel"
    "dOptions\030\311\334\003 \001(\010:\005false:=\n\021diff_encode_f"
    "ield\022\035.google.protobuf.FieldOptions\030\312\334\003 "
    "\001(\005:\0010:<\n\014delta_ignore\022\035.google.protobuf"
    ".FieldOptions\030\313\334\003 \001(\010:\005false:A\n\023untruste"
    "d_delta_max\022\035.google.protobuf.FieldOptio"
    "ns\030\320\334\003 \001(\005:\003256:\?\n\023steamml_max_entries\022\035"
    ".google.protobuf.FieldOptions\030\314\334\003 \001(\r:\0010"
    ":D\n\024steamml_is_timestamp\022\035.google.protob"
    "uf.FieldOptions\030\315\334\003 \001(\010:\005false:<\n\020steaml"
    "earn_count\022\035.google.protobuf.FieldOption"
    "s\030\316\334\003 \001(\r:\0010:u\n\025debugprint_visibility\022\035."
    "google.protobuf.FieldOptions\030\317\334\003 \001(\0162\025.E"
    "ProtoDebugVisiblity:\036k_EProtoDebugVisibi"
    "lity_Always:@\n\024schema_friendly_name\022!.go"
    "ogle.protobuf.EnumValueOptions\030\350\007 \001(\t:>\n"
    "\022schema_description\022!.google.protobuf.En"
    "umValueOptions\030\351\007 \001(\t:F\n\032schema_suppress"
    "_enumerator\022!.google.protobuf.EnumValueO"
    "ptions\030\352\007 \001(\010"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_valveextensions_2eproto_deps[1] = {
        &::descriptor_table_google_2fprotobuf_2fdescriptor_2eproto,
};
static ::absl::once_flag descriptor_table_valveextensions_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_valveextensions_2eproto = {
    false,
    false,
    1173,
    descriptor_table_protodef_valveextensions_2eproto,
    "valveextensions.proto",
    &descriptor_table_valveextensions_2eproto_once,
    descriptor_table_valveextensions_2eproto_deps,
    1,
    0,
    schemas,
    file_message_globals,
    TableStruct_valveextensions_2eproto::offsets,
    file_level_enum_descriptors_valveextensions_2eproto,
    file_level_service_descriptors_valveextensions_2eproto,
};
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
EProtoDebugVisiblity_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_valveextensions_2eproto);
  return file_level_enum_descriptors_valveextensions_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t EProtoDebugVisiblity_internal_data_[] = {
    65536u, 128u, 0u, 0u, 33587232u, 8u, };
PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::_pbi::ExtensionIdentifier<
        ::google::protobuf::MessageOptions, ::_pbi::PrimitiveTypeTraits< bool >, 8, false>
        codegen_delta_encoder(kCodegenDeltaEncoderFieldNumber, false);
PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::_pbi::ExtensionIdentifier<
        ::google::protobuf::FieldOptions, ::_pbi::PrimitiveTypeTraits< bool >, 8, false>
        valve_map_field(kValveMapFieldFieldNumber, false);
PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::_pbi::ExtensionIdentifier<
        ::google::protobuf::FieldOptions, ::_pbi::PrimitiveTypeTraits< bool >, 8, false>
        valve_map_key(kValveMapKeyFieldNumber, false);
PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::_pbi::ExtensionIdentifier<
        ::google::protobuf::FieldOptions, ::_pbi::PrimitiveTypeTraits< ::int32_t >, 5, false>
        diff_encode_field(kDiffEncodeFieldFieldNumber, 0);
PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::_pbi::ExtensionIdentifier<
        ::google::protobuf::FieldOptions, ::_pbi::PrimitiveTypeTraits< bool >, 8, false>
        delta_ignore(kDeltaIgnoreFieldNumber, false);
PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::_pbi::ExtensionIdentifier<
        ::google::protobuf::FieldOptions, ::_pbi::PrimitiveTypeTraits< ::int32_t >, 5, false>
        untrusted_delta_max(kUntrustedDeltaMaxFieldNumber, 256);
PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::_pbi::ExtensionIdentifier<
        ::google::protobuf::FieldOptions, ::_pbi::PrimitiveTypeTraits< ::uint32_t >, 13, false>
        steamml_max_entries(kSteammlMaxEntriesFieldNumber, 0u);
PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::_pbi::ExtensionIdentifier<
        ::google::protobuf::FieldOptions, ::_pbi::PrimitiveTypeTraits< bool >, 8, false>
        steamml_is_timestamp(kSteammlIsTimestampFieldNumber, false);
PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::_pbi::ExtensionIdentifier<
        ::google::protobuf::FieldOptions, ::_pbi::PrimitiveTypeTraits< ::uint32_t >, 13, false>
        steamlearn_count(kSteamlearnCountFieldNumber, 0u);
PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::_pbi::ExtensionIdentifier<
        ::google::protobuf::FieldOptions, ::_pbi::EnumTypeTraits< ::EProtoDebugVisiblity>, 14, false>
        debugprint_visibility(kDebugprintVisibilityFieldNumber, static_cast< ::EProtoDebugVisiblity >(0));
const std::string schema_friendly_name_default("");
PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::_pbi::ExtensionIdentifier<
        ::google::protobuf::EnumValueOptions, ::_pbi::StringTypeTraits, 12, false>
        schema_friendly_name(kSchemaFriendlyNameFieldNumber, schema_friendly_name_default);
const std::string schema_description_default("");
PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::_pbi::ExtensionIdentifier<
        ::google::protobuf::EnumValueOptions, ::_pbi::StringTypeTraits, 12, false>
        schema_description(kSchemaDescriptionFieldNumber, schema_description_default);
PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::_pbi::ExtensionIdentifier<
        ::google::protobuf::EnumValueOptions, ::_pbi::PrimitiveTypeTraits< bool >, 8, false>
        schema_suppress_enumerator(kSchemaSuppressEnumeratorFieldNumber, false);
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_valveextensions_2eproto),
        ::_pbi::ExtensionSet::RegisterExtension(
            &::google::protobuf::MessageOptions::default_instance(), 61000, 8,
            false, false, /*is_utf8=*/false),
        ::_pbi::ExtensionSet::RegisterExtension(
            &::google::protobuf::FieldOptions::default_instance(), 61000, 8,
            false, false, /*is_utf8=*/false),
        ::_pbi::ExtensionSet::RegisterExtension(
            &::google::protobuf::FieldOptions::default_instance(), 61001, 8,
            false, false, /*is_utf8=*/false),
        ::_pbi::ExtensionSet::RegisterExtension(
            &::google::protobuf::FieldOptions::default_instance(), 61002, 5,
            false, false, /*is_utf8=*/false),
        ::_pbi::ExtensionSet::RegisterExtension(
            &::google::protobuf::FieldOptions::default_instance(), 61003, 8,
            false, false, /*is_utf8=*/false),
        ::_pbi::ExtensionSet::RegisterExtension(
            &::google::protobuf::FieldOptions::default_instance(), 61008, 5,
            false, false, /*is_utf8=*/false),
        ::_pbi::ExtensionSet::RegisterExtension(
            &::google::protobuf::FieldOptions::default_instance(), 61004, 13,
            false, false, /*is_utf8=*/false),
        ::_pbi::ExtensionSet::RegisterExtension(
            &::google::protobuf::FieldOptions::default_instance(), 61005, 8,
            false, false, /*is_utf8=*/false),
        ::_pbi::ExtensionSet::RegisterExtension(
            &::google::protobuf::FieldOptions::default_instance(), 61006, 13,
            false, false, /*is_utf8=*/false),
        ::_pbi::ExtensionSet::RegisterEnumExtension(
            &::google::protobuf::FieldOptions::default_instance(), 61007, 14,
            false, false, ::EProtoDebugVisiblity_internal_data_),
        ::_pbi::ExtensionSet::RegisterExtension(
            &::google::protobuf::EnumValueOptions::default_instance(), 1000, 12,
            false, false, /*is_utf8=*/false),
        ::_pbi::ExtensionSet::RegisterExtension(
            &::google::protobuf::EnumValueOptions::default_instance(), 1001, 12,
            false, false, /*is_utf8=*/false),
        ::_pbi::ExtensionSet::RegisterExtension(
            &::google::protobuf::EnumValueOptions::default_instance(), 1002, 8,
            false, false, /*is_utf8=*/false),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
